### ISSUE TITLE
python fails to load

### ISSUE THREAD

**Issue by Masterskitz** [Source-Python-Dev-Team/Source.Python#117]
Been running a cs:go server for a while now, and I saw that the wcs crew have released a beta for csgo. Upon adding python to my server, this is the error it gets and cant get past. Please someone let me know where I'm going wrong with this.

```
[Source.Python] Loading...
Traceback (most recent call last):
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 42, in load
    setup_logging()
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 85, in setup_logging
    from core.settings import _core_settings
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/core/settings.py", line 15, in <module>
    from auth.paths import AUTH_PROVIDER_PATH
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/auth/__init__.py", line 12, in <module>
    from translations.strings import LangStrings
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/translations/strings.py", line 10, in <module>
    from binascii import unhexlify
ImportError: libz.so.1: cannot open shared object file: No such file or directory
[Source.Python] Failed to load the main module.
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
Traceback (most recent call last):
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 56, in unload
    unload_plugins()
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/__init__.py", line 250, in unload_plugins
    from core.manager import core_plugin_manager
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/core/manager.py", line 12, in <module>
    from plugins.manager import PluginManager
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/plugins/__init__.py", line 12, in <module>
    from translations.strings import LangStrings
  File "/home/servers/csgo/dev/csgo/addons/source-python/packages/source-python/translations/strings.py", line 10, in <module>
    from binascii import unhexlify
ImportError: libz.so.1: cannot open shared object file: No such file or directory
[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.
```

**Comment by Ayuto** [comment]
The libz library is missing on your server. Make sure to install the 32 bit version if your architecture is 64 bit.
