### ISSUE TITLE
CSCO Support

### ISSUE THREAD

**Issue by Hackmastr** [Source-Python-Dev-Team/Source.Python#174]
Hello,
There's a mod for CSGO called CS: Classic Offensive, I've tried  loading  SP with  it, but  it crashes.  
Is is possible to support the mod?
https://reddit.com/r/ClassicOffensive

Log:  
http://pastebin.com/r071BtSW

**Comment by satoon101** [comment]
It would be easy enough to fix that error, which I will do shortly.  The longer fix, to get the game fully supported, will take more time.  We currently have all CS:GO modules setup to use the engine and not game-specific within the engine.  I would be interested in knowing which of those we can and can't continue to utilize as such in regards to CS:CO.  But, again, that will take time to figure out.  I am away from my PC for the next week, so I cannot test anything myself.

**Comment by satoon101** [comment]
@Hackmastr - could you please try with SP build (minimum) 511 and let us know if that fixes your crashing and loading of SP.  Again, further support will have to come later.  We just want to make sure you're able to load SP properly for the time being.

**Comment by Hackmastr** [comment]
@satoon101 It works! Thanks!
Will CSCO be supported separately? Or just CSGO.

**Comment by Hackmastr** [comment]
@satoon101 It doesn't work, it's still crashing.

Log: http://pastebin.com/8TFhjU0h

**Comment by satoon101** [comment]
Whoops...That's what happens when I make changes without the ability to test.  Ok, I'll fix that real quick.  Try version 512 once it is available.

**Comment by Hackmastr** [comment]
@satoon101 not working yet, still crashing 😄 

```
Failed to load gamerulescvars.txt, game rules cvars might not be reported to management tools.
Server is hibernating
No web api auth key specified - workshop downloads will be disabled.
[Source.Python] Loading...

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\__init__.py", line 47, in load
    setup_sp_command()
  File "..\addons\source-python\packages\source-python\__init__.py", line 203, in setup_sp_command
    from core.command import auth, docs, dump, plugin
  File "..\addons\source-python\packages\source-python\core\command\__init__.py", line 14, in <module>
    from commands.typed import TypedServerCommand
  File "..\addons\source-python\packages\source-python\commands\typed.py", line 30, in <module>
    from filters.players import parse_filter
  File "..\addons\source-python\packages\source-python\filters\players.py", line 26, in <module>
    from players.entity import Player
  File "..\addons\source-python\packages\source-python\players\entity.py", line 43, in <module>
    engine=SOURCE_ENGINE,
  File "..\addons\source-python\packages\source-python\players\engines\csgo\__init__.py", line 29, in <module>
    from players._base import Player as _Player
  File "..\addons\source-python\packages\source-python\players\_base.py", line 68, in <module>
    from weapons.entity import Weapon
  File "..\addons\source-python\packages\source-python\weapons\entity.py", line 43, in <module>
    engine=SOURCE_ENGINE,
  File "..\addons\source-python\packages\source-python\weapons\engines\csgo\__init__.py", line 18, in <module>
    for weapon, values in weapon_manager.ini['weapons'].items()
  File "..\addons\source-python\packages\source-python\weapons\default.py", line 29, in __getattribute__
    'No support for game "{0}"'.format(GAME_NAME))

NotImplementedError: No support for game "csco"


[Source.Python] Failed to load the main module.
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\__init__.py", line 58, in unload
    unload_plugins()
  File "..\addons\source-python\packages\source-python\__init__.py", line 311, in unload_plugins
    from core.command import _core_command
  File "..\addons\source-python\packages\source-python\core\command\__init__.py", line 14, in <module>
    from commands.typed import TypedServerCommand
  File "..\addons\source-python\packages\source-python\commands\typed.py", line 30, in <module>
    from filters.players import parse_filter
  File "..\addons\source-python\packages\source-python\filters\players.py", line 26, in <module>
    from players.entity import Player
  File "..\addons\source-python\packages\source-python\players\entity.py", line 43, in <module>
    engine=SOURCE_ENGINE,
  File "..\addons\source-python\packages\source-python\players\engines\csgo\__init__.py", line 29, in <module>
    from players._base import Player as _Player
  File "..\addons\source-python\packages\source-python\players\_base.py", line 68, in <module>
    from weapons.entity import Weapon
  File "..\addons\source-python\packages\source-python\weapons\entity.py", line 43, in <module>
    engine=SOURCE_ENGINE,
  File "..\addons\source-python\packages\source-python\weapons\engines\csgo\__init__.py", line 18, in <module>
    for weapon, values in weapon_manager.ini['weapons'].items()
  File "..\addons\source-python\packages\source-python\weapons\default.py", line 29, in __getattribute__
    'No support for game "{0}"'.format(GAME_NAME))

NotImplementedError: No support for game "csco"


[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.
```

**Comment by satoon101** [comment]
@Hackmastr - please try with version 513.  The latest change should fix that error.

**Comment by Hackmastr** [comment]
@satoon101 sweet! It works now! Thanks!

A question:
Will CSCO be supported separately?

**Comment by satoon101** [comment]
That probably depends on how difficult it is to support.  I haven't tried the game out, myself, and can't until next week at the earliest.

**Comment by Ayuto** [comment]
What are we actually still missing for this to be closed?

**Comment by satoon101** [comment]
We don't specifically support CS:CO in any fashion, but SP does load.  I never got it working locally to really test anything.  Though, it was never really on top of my priority list to do so.

I am fine with closing it.  I am not sure how popular that mod is these days anyway.
