### ISSUE TITLE
SP fails to load on newest CS:GO Update 5/18/17 (5/19/17 UTC, 1.35.8.0)

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#198]
Hey,

Source Python fails to load on the newest CS:GO Update 5/18/17 (5/19/17 UTC, 1.35.8.0).

Windows 10 atleast, cant confirm on **Linux.**

```[Source.Python] Loading...
D:\GameServer\csgo_timer\csgo\addons\source-python\packages\source-python\__init__.py:390: UserWarning: sys.stdout and/or sys.stderr is None. All data will be redirected through core.console_message() instead. If you receive this warning, please notify us and tell us your operating system, game and Source.Python version. The information can be posted here: https://github.com/Source-Python-Dev-Team/Source.Python/issues/175. Source.Python should continue working, but we would like to figure out in which situations sys.stdout is None to be able to fix this issue instead of applying a workaround.
  'sys.stdout and/or sys.stderr is None. All data will be redirected through '

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\__init__.py", line 47, in load
    setup_global_pointers()
  File "..\addons\source-python\packages\source-python\__init__.py", line 169, in setup_global_pointers
    SP_DATA_PATH / 'memory' / 'global_pointers.ini'))
  File "..\addons\source-python\packages\source-python\memory\manager.py", line 759, in create_global_pointers_from_file
    self.global_pointer(cls, *data)
  File "..\addons\source-python\packages\source-python\memory\manager.py", line 728, in global_pointer
    ptr = binary.find_pointer(identifier, offset, level)

ValueError: Could not find signature: 64a12c0000008b0d2a2a2a2a8b0c88a12a2a2a2a3b81040000007e2a682a2a2a2ae82a2a2a2a83c404833d2a2a2a2aff752a83ec0cc705

[Source.Python] Failed to load the main module.
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\__init__.py", line 60, in unload
    remove_entities_listener()
  File "..\addons\source-python\packages\source-python\__init__.py", line 289, in remove_entities_listener
    manager.get_global_pointer('GlobalEntityList').remove_entity_listener(
  File "..\addons\source-python\packages\source-python\memory\manager.py", line 769, in get_global_pointer
    raise NameError('No global pointer found for "{0}".'.format(name))

NameError: No global pointer found for "GlobalEntityList".


[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.```

**Comment by KirillMysnik** [comment]
7d0e99c857220a43763515c0a6a6d6d769097cdd should fix this issue.

**Comment by KirillMysnik** [comment]
> Frag: Yep, its fixed

Also works for me. Closing.
