### ISSUE TITLE
Sound precaching broken?

### ISSUE THREAD

**Issue by njanke96** [Source-Python-Dev-Team/Source.Python#225]
I took a break from developing a plugin and came back to find this error after updating to the most recent sp build (612):

```
[SP] Loading plugin 'inf_timer'...

[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/plugins/command.py", line 162, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "../addons/source-python/packages/source-python/plugins/manager.py", line 193, in load
    plugin._load()
  File "../addons/source-python/packages/source-python/plugins/instance.py", line 76, in _load
    self.module.load()
  File "../addons/source-python/plugins/inf_timer/inf_timer.py", line 28, in load
    precache_resources()
  File "../addons/source-python/plugins/inf_timer/core/resources.py", line 20, in precache_resources
    StreamSound(sound_mapwr, download=True).precache()
  File "../addons/source-python/packages/source-python/engines/sound.py", line 364, in precache
    string_tables.soundprecache.add_string(

AttributeError: 'NoneType' object has no attribute 'add_string'


[SP] Plugin 'inf_timer' was unable to be loaded.
```

I noticed changes to sound.py in recent commits. Is there something wrong/obsolete with the way I'm precaching my custom sounds?

```python
def precache_resources():
    # precache sounds (and add to download table)
    sound_mapwr = ConVar('tmr_sound_mapwr').get_string()
    sound_stagewr = ConVar('tmr_sound_stagewr').get_string()
    sound_top10 = ConVar('tmr_sound_top10').get_string()
    sound_pr = ConVar('tmr_sound_pr').get_string()
    sound_completion = ConVar('tmr_sound_completion').get_string()

    StreamSound(sound_mapwr, download=True).precache()
    StreamSound(sound_stagewr, download=True).precache()
    StreamSound(sound_top10, download=True).precache()
    StreamSound(sound_pr, download=True).precache()
    StreamSound(sound_completion, download=True).precache()
```

**Comment by satoon101** [comment]
You shouldn't be calling the `precache` method yourself, as the Sound classes handle that internally.  We should probably make that method private to avoid further confusion.

The error happens because you are loading the plugin when there is no map loaded (probably in your autoexec.cfg file).  At that time, the stringtables are not allocated, so they return `None`.

**Comment by njanke96** [comment]
Ok, so instantiation of a StreamSound will precache the sound automatically?

**Comment by satoon101** [comment]
You should set those to variables (or in a list or something), so that when you `play` the sounds, you call the `play` method of the object, which will do this:
https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/packages/source-python/engines/sound.py#L174-L193

**Comment by njanke96** [comment]
Thank you
