### ISSUE TITLE
ISADirectoryError for server command sp info

### ISSUE THREAD

**Issue by backraw** [Source-Python-Dev-Team/Source.Python#228]
Whenever I type ```sp info``` in the server console I get the following:
```
sp info

[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/commands/typed.py", line 553, in on_command
    result = cls.on_clean_command(command_info, command_node, args)
  File "../addons/source-python/packages/source-python/commands/typed.py", line 568, in on_clean_command
    return command_node.callback(command_info, *cleaned_args)
  File "../addons/source-python/packages/source-python/core/command/__init__.py", line 132, in print_info
    result += '\nOS            : {}'.format(platform.platform())
  File "../addons/source-python/Python3/platform.py", line 1360, in platform
    libcname, libcversion = libc_ver(sys.executable)
  File "../addons/source-python/Python3/platform.py", line 169, in libc_ver
    with open(executable, 'rb') as f:

IsADirectoryError: [Errno 21] Is a directory: '../addons/source-python/Python3'
```
I don't know how to fix it myself to be honest. It's not of high priority anyway. Just wanted to point you at it :)

The error occurs in build #616 for CS:GO and CS:S as far as I can tell.

**Comment by Ayuto** [comment]
Thanks! The last commit should fix the error.
