### ISSUE TITLE
Unable to load plugin on server start

### ISSUE THREAD

**Issue by WookieWarlordNZ** [Source-Python-Dev-Team/Source.Python#239]
Hi all,

I had a good look through the search function on this sub-forum but was unable to find someone else with the same issue I am getting when trying to load source-python for my css linux server (renting it).

This is what console spits out during boot.
[Source.Python] Loading...
[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):
 
  File "/home/tcagame/wookie/4/cstrike/addons/source-python/packages/source-python/__init__.py", line 86, in load
    setup_core_settings()
 
  File "/home/tcagame/wookie/4/cstrike/addons/source-python/packages/source-python/__init__.py", line 181, in setup_core_settings
    from core.settings import _core_settings
 
  File "/home/tcagame/wookie/4/cstrike/addons/source-python/packages/source-python/core/__init__.py", line 29, in <module>
    from urllib.request import urlopen
 
  File "/home/tcagame/wookie/4/cstrike/addons/source-python/Python3/urllib/request.py", line 84, in <module>
    import base64
 
  File "/home/tcagame/wookie/4/cstrike/addons/source-python/Python3/base64.py", line 11, in <module>
    import binascii
 
ImportError: libz.so.1: cannot open shared object file: No such file or directory
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Failed to unload the main module.
[Source.Python] Unloaded successfully.

I am using the source-python-css-january-22 version of the installer from [http://builds.sourcepython.com/job/Source.Python/lastSuccessfulBuild/](url)

Please help, been trying to get this working to no avail for a few days now.

**Comment by invincibleqc** [comment]
→ https://github.com/Source-Python-Dev-Team/Source.Python/issues/117

**Comment by Ayuto** [comment]
See also:
http://wiki.sourcepython.com/general/installation.html
