### ISSUE TITLE
Danger Zone Support

### ISSUE THREAD

**Issue by xancara** [Source-Python-Dev-Team/Source.Python#267]
Got a couple of items that are not being accounted for that are causing a crash sometimes. It isn't super consistent that it causes a full server crash but it happens occasionally.

> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_fists'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_fists'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_tablet'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_tablet'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_fists'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_fists'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_tablet'
> [SP] Caught an Exception:
> Traceback (most recent call last):
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
> make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
> File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
> weapon_name = weapon_manager[weapon].basename
> File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
> return super().__getitem__(name)
> KeyError: 'weapon_tablet'

**Comment by Ayuto** [comment]
Could you please re-post the traceback using code blocks?
https://help.github.com/articles/creating-and-highlighting-code-blocks/#fenced-code-blocks

Also, please post the output of ``sp info``.

**Comment by xancara** [comment]
As requested:

```python
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_fists'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_fists'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_tablet'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_tablet'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_fists'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_fists'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_tablet'
[SP] Caught an Exception:
Traceback (most recent call last):
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 389, in _on_weapon_bump
make_object(Player, args[0]), edict_from_pointer(args[1]).classname)
File "../addons/source-python/packages/source-python/weapons/restrictions.py", line 62, in on_player_bumping_weapon
weapon_name = weapon_manager[weapon].basename
File "../addons/source-python/packages/source-python/weapons/manager.py", line 93, in __getitem__
return super().__getitem__(name)
KeyError: 'weapon_tablet'
```

SP INFO output
```python
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum : 9ebc5367cb41f385aa124a9387964dd9
Date : 2018-12-20 17:55:40.600288
OS : Linux-4.16.8-nfo-xen-x86_64-Intel-R-_Xeon-R-_CPU_E5-2697_v3_@_2.60GHz-with-gentoo-2.4.1
Game : csgo
SP version : 675
Github commit : f711ebe88122ddaa7b55dd94c69959dbb8b6c807
Server plugins:
00: Source.Python, (C) 2012-2018, Source.Python Team.
01: Metamod:Source 1.10.7-dev
SP plugins:
00: es_emulator, https://github.com/Ayuto/EventScripts-Emulator
01: wcs, 2018.12.17-2, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
--------------------------------------------------------

```

**Comment by vinci6k** [comment]
I'm guessing we need to add the data for the [new weapons and items](https://pastebin.com/K3NjrR1q) to the [csgo.ini](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/data/source-python/weapons/csgo.ini) file to fix those errors.

As for the crashes though, I think you need to precache the models for the new weapons before spawning them, cause the game doesn't do that unless you are using the correct gamemode (**game_type 6** and **game_mode 0** for Danger Zone).

**Comment by Ayuto** [comment]
Yeah, the crashes shouldn't be caused by the exception. Nevertheless, we should add the weapons to csgo.ini.

@xancara 
Here is another hint for posting:
Don't add the ``python`` tag to your code blocks. It's not python code what you are posting. It's just text.

Have you figured out any steps to reproduce the crash?

**Comment by xancara** [comment]
I can't get the crash to happen consistently nor can I purposely reproduce it. When it does happen, it happens while joining the server. I will give you the output from the server debug log.

I will note that this only seems to happen in DZ. I have launched and loaded in the normal server about 100 times or so restarting the server each attempt with no crashes (classic casual). With DZ, doing the same thing, I get about a crash about every, 10 or so attempts at joining. It hasn't happened since this dump below though.

Here is the console output as it crashes 
```
PreMinidumpCallback: updating dump comment
Uploading dump (in-process) [proxy '']
/tmp/dumps/assert_20181220031029_1.dmp
./exec_agwcsdz.run: line 318: 26803 Bus error               (core dumped) $HL_CMD
Error while mapping shared library sections:
`/servers/agwcsdz/csgo/addons/source-python/bin/core.so': not in executable format: File truncated
```

Here is the actual dmp
```
----------------------------------------------
CRASH: Thu Dec 20 12:50:13 EST 2018
Start Line: ./srcds_linux -game csgo -ip <IPADDRESS REMOVED> +maxplayers 12 -maxplayers_override 12 -debug -console -usercon -nocrashdialog -norestart -nodefaultmap +host_timer_spin_ms 0 +sv_pure 0 -tickrate 100
[New LWP 26803]
[New LWP 26824]
[New LWP 26817]
[New LWP 26820]
[New LWP 26818]
[New LWP 26816]
[New LWP 26813]
[New LWP 26811]
[New LWP 29519]
[New LWP 29464]
[New LWP 26831]
[New LWP 26829]
[New LWP 26828]
[New LWP 26827]
[New LWP 26826]
[New LWP 26810]
[New LWP 26809]
[New LWP 26804]
[New LWP 26825]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `./srcds_linux -game csgo -ip <IPADDRESS REMOVED> +maxplayers 12 -maxplayers_override'.
Program terminated with signal SIGBUS, Bus error.
#0  0xf7f9b59e in ?? () from /lib/ld-linux.so.2
[Current thread is 1 (Thread 0xf7cb8700 (LWP 26803))]
#0  0xf7f9b59e in ?? () from /lib/ld-linux.so.2
#1  0xf7fa6805 in ?? () from /lib/ld-linux.so.2
#2  0xf7df7135 in _dl_catch_error () from /lib32/libc.so.6
#3  0xf7fa6309 in ?? () from /lib/ld-linux.so.2
#4  0xf7eb8c71 in ?? () from /lib32/libdl.so.2
#5  0xf7df7135 in _dl_catch_error () from /lib32/libc.so.6
#6  0xf7eb946e in ?? () from /lib32/libdl.so.2
#7  0xf7eb8d1e in dlopen () from /lib32/libdl.so.2
#8  0xf30b93e3 in __wrap_dlopen () from /servers/agwcsdz/bin/crashhandler.so
#9  0xf30a8ccd in ?? () from /servers/agwcsdz/bin/crashhandler.so
#10 0xf30a9bec in ?? () from /servers/agwcsdz/bin/crashhandler.so
#11 0xf30ac5f8 in ?? () from /servers/agwcsdz/bin/crashhandler.so
#12 0xf30c4c27 in ?? () from /servers/agwcsdz/bin/crashhandler.so
#13 0xf30c4e02 in ?? () from /servers/agwcsdz/bin/crashhandler.so
#14 0xf30c4f36 in ?? () from /servers/agwcsdz/bin/crashhandler.so
#15 <signal handler called>
#16 0xf6516aa2 in ?? () from /servers/agwcsdz/bin/engine.so
#17 0xf64fd6ae in ?? () from /servers/agwcsdz/bin/engine.so
#18 0xf64febb7 in ?? () from /servers/agwcsdz/bin/engine.so
#19 0xf65b41fe in ?? () from /servers/agwcsdz/bin/engine.so
#20 0xf65b4e9c in ?? () from /servers/agwcsdz/bin/engine.so
#21 0xf65b5608 in ?? () from /servers/agwcsdz/bin/engine.so
#22 0xf65be9e4 in ?? () from /servers/agwcsdz/bin/engine.so
#23 0xf65becb6 in ?? () from /servers/agwcsdz/bin/engine.so
#24 0xf65bedc9 in ?? () from /servers/agwcsdz/bin/engine.so
#25 0xf6625aca in ?? () from /servers/agwcsdz/bin/engine.so
#26 0xf66229b6 in ?? () from /servers/agwcsdz/bin/engine.so
#27 0xf771a54d in ?? () from /servers/agwcsdz/bin/dedicated.so
#28 0xf771a5d8 in ?? () from /servers/agwcsdz/bin/dedicated.so
#29 0xf6622aad in ?? () from /servers/agwcsdz/bin/engine.so
#30 0xf675a3f0 in ?? () from /servers/agwcsdz/bin/engine.so
#31 0xf6623ca5 in ?? () from /servers/agwcsdz/bin/engine.so
#32 0xf771a6b4 in ?? () from /servers/agwcsdz/bin/dedicated.so
#33 0xf777b2d0 in ?? () from /servers/agwcsdz/bin/dedicated.so
#34 0xf777b2d0 in ?? () from /servers/agwcsdz/bin/dedicated.so
#35 0xf7713c73 in ?? () from /servers/agwcsdz/bin/dedicated.so
#36 0x080486f9 in main ()
No symbol table info available.
eax            0xf16a2ed8	-244699432
ecx            0xffffffff	-1
edx            0xf16a2f20	-244699360
ebx            0xf7fb8fcc	-134508596
esp            0x96c8ee8	0x96c8ee8
ebp            0x9688890	0x9688890
esi            0xf30e5e6f	-217162129
edi            0xf6ca1fc3	-154525757
eip            0xf7f9b59e	0xf7f9b59e
eflags         0x10216	[ PF AF IF RF ]
cs             0x23	35
ss             0x2b	43
ds             0x2b	43
es             0x2b	43
fs             0x0	0
gs             0x63	99
From        To          Syms Read   Shared Object Library
0xf7ec31d0  0xf7f4a835  Yes (*)     /lib32/libm.so.6
0xf7eb8ab0  0xf7eb9bc4  Yes (*)     /lib32/libdl.so.2
0xf7e9c910  0xf7ead87f  Yes (*)     /lib32/libpthread.so.0
0xf7cd1ea0  0xf7e26446  Yes (*)     /lib32/libc.so.6
0xf7f938f0  0xf7fae2cb  Yes (*)     /lib/ld-linux.so.2
0xf7c77440  0xf7c9407c  Yes (*)     /servers/agwcsdz/bin/libtier0.so
0xf7c13c80  0xf7c4765c  Yes (*)     /servers/agwcsdz/bin/libvstdlib.so
0xf7713920  0xf77a471c  Yes (*)     /servers/agwcsdz/bin/dedicated.so
0xf76d4d60  0xf76ea1b4  Yes (*)     /servers/agwcsdz/bin/libsteam_api.so
0xf7531660  0xf7612f74  Yes (*)     /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/32/libstdc++.so.6
0xf74ade04  0xf74bd4b8  Yes         /servers/agwcsdz/bin/libgcc_s.so.1
0xf6427650  0xf6861874  Yes (*)     /servers/agwcsdz/bin/engine.so
0xf609f800  0xf6277af4  Yes (*)     /servers/agwcsdz/bin/libsteamnetworkingsockets.so
0xf6ca28b0  0xf6ca6734  Yes (*)     /lib32/librt.so.1
0xf5a3b980  0xf5b28eec  Yes (*)     /servers/agwcsdz/bin/materialsystem.so
0xf54c53b0  0xf558392c  Yes (*)     /servers/agwcsdz/bin/studiorender.so
0xf52f1450  0xf5424218  Yes (*)     /servers/agwcsdz/bin/vphysics.so
0xf51c9ef0  0xf5250694  Yes (*)     /servers/agwcsdz/bin/datacache.so
0xf50ea630  0xf51693b4  Yes (*)     /servers/agwcsdz/bin/vscript.so
0xf6c0e590  0xf6c2e4f0  Yes (*)     /servers/agwcsdz/bin/shaderapiempty.so
0xf31cfd00  0xf40c9444  Yes (*)     /servers/agwcsdz/bin/steamclient.so
0xf30a7ba0  0xf30e5e34  Yes (*)     /servers/agwcsdz/bin/crashhandler.so
0xf2fef0d0  0xf3050898  Yes (*)     /servers/agwcsdz/csgo/bin/matchmaking_ds.so
0xf1ca2e80  0xf288d590  Yes (*)     /servers/agwcsdz/csgo/bin/server.so
0xf189ed70  0xf18d4230  Yes (*)     /servers/agwcsdz/bin/soundemittersystem.so
0xf185f820  0xf187e40c  Yes (*)     /servers/agwcsdz/bin/scenefilecache.so
0xf16772b0  0xf1699134  Yes (*)     /servers/agwcsdz/csgo/addons/source-python.so
0xf0cde040  0xf0f79fa4  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/plat-linux/libpython3.6m.so.1.0
0xf6c03a30  0xf6c043e4  Yes (*)     /lib32/libutil.so.1
                        No          /servers/agwcsdz/csgo/addons/source-python/bin/core.so
0xf7f8d750  0xf7f8e5ce  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_heapq.cpython-36m-i386-linux-gnu.so
0xf1616970  0xf161ee04  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/math.cpython-36m-i386-linux-gnu.so
0xefef8350  0xeff06434  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_datetime.cpython-36m-i386-linux-gnu.so
0xf7f86190  0xf7f88fb8  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/zlib.cpython-36m-i386-linux-gnu.so
0xefe5ebc0  0xefe6be49  Yes (*)     /usr/lib32/libz.so.1
0xf1610ea0  0xf1612392  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_bz2.cpython-36m-i386-linux-gnu.so
0xefe4c010  0xefe58144  Yes (*)     /usr/lib32/libbz2.so.1.0
0xf1608660  0xf160bbc1  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_lzma.cpython-36m-i386-linux-gnu.so
0xefe12460  0xefe2bd24  Yes (*)     /usr/lib32/liblzma.so.5
0xf1603b10  0xf16041c2  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/grp.cpython-36m-i386-linux-gnu.so
0xefe46390  0xefe48254  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_hashlib.cpython-36m-i386-linux-gnu.so
0xefc45640  0xefd45734  Yes (*)     /usr/lib32/libcrypto.so.1.0.0
0xefe02270  0xefe0cd24  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_blake2.cpython-36m-i386-linux-gnu.so
0xefbfe760  0xefc04104  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_sha3.cpython-36m-i386-linux-gnu.so
0xefe417d0  0xefe4200a  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_bisect.cpython-36m-i386-linux-gnu.so
0xefe3dc30  0xefe3e8b1  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_random.cpython-36m-i386-linux-gnu.so
0xf6c00610  0xf6c0085a  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_opcode.cpython-36m-i386-linux-gnu.so
0xefb38e40  0xefb39f34  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_posixsubprocess.cpython-36m-i386-linux-gnu.so
0xefb32420  0xefb344ed  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/select.cpython-36m-i386-linux-gnu.so
0xefb279e0  0xefb2bed2  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_struct.cpython-36m-i386-linux-gnu.so
0xefb1fde0  0xefb221e4  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/binascii.cpython-36m-i386-linux-gnu.so
0xefac68b0  0xefad4804  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_socket.cpython-36m-i386-linux-gnu.so
0xef969440  0xef96f91e  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_json.cpython-36m-i386-linux-gnu.so
0xef911bc0  0xef9203a4  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_pickle.cpython-36m-i386-linux-gnu.so
0xef7c43c0  0xef7fab54  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_decimal.cpython-36m-i386-linux-gnu.so
0xef3a83a0  0xef3ab114  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/unicodedata.cpython-36m-i386-linux-gnu.so
0xef38bb60  0xef392b04  Yes (*)     /lib32/libnss_files.so.2
0xef383b50  0xef386af4  Yes (*)     /lib32/libnss_dns.so.2
0xef36d640  0xef379f94  Yes (*)     /lib32/libresolv.so.2
0xef39ed20  0xef3a3c6c  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/audioop.cpython-36m-i386-linux-gnu.so
0xef2e5210  0xef2e7274  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/mmap.cpython-36m-i386-linux-gnu.so
0xef18c2e0  0xef19b294  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_ctypes.cpython-36m-i386-linux-gnu.so
0xef1710f0  0xef1752e4  Yes (*)     /usr/lib32/libffi.so.6
0xef0b8400  0xef14b814  Yes (*)     /servers/agwcsdz/csgo/addons/source-python/Python3/plat-linux/libsqlite3.so.0
0xef0a3100  0xef0a4c2d  Yes (*)     /servers/agwcsdz/csgo/../csgo/addons/metamod/bin/server.so
0xef0686b0  0xef096912  Yes (*)     /servers/agwcsdz/csgo/../csgo/addons/metamod/bin/metamod.2.csgo.so
0xeefd7f50  0xeeff5884  Yes         /servers/agwcsdz/csgo/addons/source-python/packages/custom/muparser.cpython-36m-i386-linux-gnu.so
0xeee419a0  0xeee48814  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_sqlite3.cpython-36m-i386-linux-gnu.so
0xef399320  0xef399d74  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/termios.cpython-36m-i386-linux-gnu.so
0xef17b380  0xef183284  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/_elementtree.cpython-36m-i386-linux-gnu.so
0xee183970  0xee1aac84  Yes         /servers/agwcsdz/csgo/addons/source-python/Python3/lib-dynload/pyexpat.cpython-36m-i386-linux-gnu.so
0xf1600950  0xf1600eb8  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/bin/sourcemod_mm_i486.so
0xed2099b0  0xed37c849  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/bin/sourcemod.2.csgo.so
0xed14b9a0  0xed1a2120  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/bin/sourcemod.logic.so
0xed554280  0xed577e7c  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/bin/sourcepawn.jit.x86.so
0xedf174f0  0xedf1a324  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/updater.ext.so
0xed51ea60  0xed546df5  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/webternet.ext.so
0xebe27140  0xebe46c42  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/game.cstrike.ext.2.csgo.so
0xedf10c90  0xedf144d8  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/bintools.ext.so
0xebca9390  0xebce2132  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/sdktools.ext.2.csgo.so
0xedf07780  0xedf0df68  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/topmenus.ext.so
0xed50fac0  0xed5145d4  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/clientprefs.ext.so
0xeaa65e30  0xeab85fc0  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/dbi.sqlite.ext.so
0xeb963700  0xeb995ed0  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/regex.ext.so
0xe9cb9f50  0xe9cd9592  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/sdkhooks.ext.2.csgo.so
0xe8c78fb0  0xe8d03d05  Yes (*)     /servers/agwcsdz/csgo/addons/sourcemod/extensions/dbi.mysql.ext.so
0xed506210  0xed50a2a4  Yes (*)     /lib32/libnss_db.so.2
(*): Shared library is missing debugging information.
End of Source crash report
----------------------------------------------
```

@Ayuto -- I was including the python tags for the syntax highlight for the vars within the stack trace for better 'at a glance' spotting. If it is your preference to have it not done, you may want to be explicit in your request.

**Comment by jordanbriere** [comment]
I'm not sure if this is still an issue or not, but since it has been inactive for 3 years and that nobody reported similar issues since I believe the cause might have been fixed so I will just go ahead and close this issue. Please re-open if you are still experience these crashes or that you have new information related to it to share. Thanks!
