### ISSUE TITLE
probleme serveur counter-strike-source avec source-python 

### ISSUE THREAD

**Issue by herlak** [Source-Python-Dev-Team/Source.Python#281]
2019-08-09 06:09:07 - sp	-	MESSAGE	[SP] Chargement du plugin 'es_emulator'...
2019-08-09 06:09:08 - sp	-	MESSAGE	[SP] Le plugin 'es_emulator' a été chargé avec succès.
2019-08-09 06:09:09 - sp	-	MESSAGE	[SP] Chargement du plugin 'gungame'...
2019-08-09 06:09:11 - sp	-	MESSAGE	[SP] Le plugin 'gungame' a été chargé avec succès.
2019-08-09 06:09:11 - sp	-	MESSAGE	[SP] Chargement du plugin 'wcs'...
2019-08-09 06:09:12 - sp	-	MESSAGE	[SP] Le plugin 'wcs' a été chargé avec succès.
2019-08-09 06:09:20 - sp	-	MESSAGE	Sub command "reload" not found.
2019-08-09 06:16:17 - sp	-	EXCEPTION	
[SP] Une erreur s'est produite:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/events/listener.py", line 92, in fire_game_event
    callback(game_event)
  File "../addons/source-python/plugins/gungame/core/listeners.py", line 198, in _player_death
    if weapon_manager[weapon].basename != killer.level_weapon:
  File "../addons/source-python/packages/source-python/weapons/manager.py", line 92, in __getitem__
    return super().__getitem__(name)

KeyError: 'weapon_env_explosion'

**Comment by jordanbriere** [comment]
Merci pour le rapport! Malheureusement, ce n'est pas une erreur causée par Source.Python mais plutôt un problème d'utilisation par le plugin [GunGame](https://github.com/GunGame-Dev-Team/GunGame-SP/issues) qui ne prend pas en compte les dommages causés par certaines entités qui ne sont pas des armes. Une solution possible pourrait être de remplacer [cette ligne](https://github.com/GunGame-Dev-Team/GunGame-SP/blob/master/addons/source-python/plugins/gungame/core/listeners.py#L198) par la ligne suivante:
```python
        if weapon not in weapon_manager or weapon_manager[weapon].basename != killer.level_weapon:
```
Pour faire en sorte de s'assurer qu'il s'agit bien d'une arme avant de la récupérer. Dans tout les cas il serait préférable de rapporter le problème sur le lien donné plus haut. 👍

**Comment by herlak** [comment]
merci pour votre aide oui après tout cela le probleme de ce plugins gungame bon journée
