### ISSUE TITLE
rendermode - int or str?

### ISSUE THREAD

**Issue by ThaPwned** [Source-Python-Dev-Team/Source.Python#29]
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\custom\rpgz\listeners\__init__.py", line 36, in __call__
    callback(*args)
  File "..\addons\source-python\plugins\rpg\skills\Stealth.py", line 82, in up
    playerentity.color = r, g, b, a
  File "..\addons\source-python\packages\source-python\entities\entity.py", line 241, in __setattr__
    super(BaseEntity, self).__setattr__(attr, value)
  File "..\addons\source-python\packages\source-python\entities\entity.py", line 312, in set_color
    self.rendermode = self.rendermode | 1
  File "..\addons\source-python\packages\source-python\entities\entity.py", line 235, in __setattr__
    self.datamaps[attr]._set_value(value)
  File "..\addons\source-python\packages\source-python\entities\datamaps.py", line 368, in _set_value
    getattr(self.current_pointer, self.set_attr)(value, self.offset)

Boost.Python.ArgumentError: Python argument types in
    Pointer.set_char(Pointer, int, int)
did not match C++ signature:
    set_char(class CPointer {lvalue}, char, int offset=0)

**Comment by satoon101** [comment]
When you get a chance, could you verify that this is fixed in the newest version?  Don't forget that when setting the color, you need to pass a Color instance and when getting the color a Color instance is returned.

**Comment by ThaPwned** [comment]
Yes, it's fixed. Thank you! Sorry for the delay as I didn't have time to test it until now.

**Comment by satoon101** [comment]
Thank you for verifying.
