### ISSUE TITLE
Segmentation fault from stack trace in loading SP

### ISSUE THREAD

**Issue by ns-phennessy** [Source-Python-Dev-Team/Source.Python#310]
**Operating System**: Ubuntu 18.04.4 LTS
**SP Version**: 695 February-22-2020 92b3adfaaaf1bb9ecd2be1ddad55bc68589b4152
**Game**: Team Fortress 2, Server Version 5615298

When booting a server, i see the following stack trace; followed by a segmentation fault.

The result is that I cannot boot with SourcePython at all. 

I have been able to run this configuration several times before, but for some reason it suddenly stopped working. I'm guessing something changed on TF2's side? 

Thing's I've tried:
- Loading without MM and SM
- Loading without any SP plugins at all
- Loading without SP works just fine

Any help would be appericiated.

<details open>
<summary>Error Message</summary>

```[Source.Python] Loading...

[SP] Encountered a Warning:
  File '../addons/source-python/packages/site-packages/mutagen/id3/_specs.py', line 666: DeprecationWarning
    invalid escape sequence \s

[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/__init__.py", line 93, in load
    setup_sp_command()

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/__init__.py", line 329, in setup_sp_command
    from core.command import auth, docs, dump, plugin

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/core/command/__init__.py", line 20, in <module>
    from commands.typed import TypedServerCommand

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/commands/typed.py", line 30, in <module>
    from filters.players import parse_filter

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/filters/players.py", line 26, in <module>
    from players.entity import Player

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/players/entity.py", line 43, in <module>
    engine=SOURCE_ENGINE,

  File "/usr/games/steam/tf2/tf/addons/soun/Python3/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/players/engines/orangebox/__init__.py", line 12, in <module>
    from players._base import Player as _Player

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/players/_base.py", line 43, in <module>
    from entities.entity import Entity

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/entities/entity.py", line 59, in <module>
    from entities._base import Entity

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/entities/_base.py", line 72, in <module>
    _projectile_weapons = [weapon.name for weapon in WeaponClassIter('grenade')]

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/entities/_base.py", line 72, in <listcomp>
    _projectile_weapons = [weapon.name for weapon in WeaponClassIter('grenade')]

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/filters/iterator.py", line 56, in __iter__
    if self._is_valid(item):

  File "/usr/games/steam/tf2/tf/addons/source-python/packages/source-python/filters/iterator.py", line 76, in _is_valid
    if not self._filters[filter_name](item):

KeyError: 'grenade'
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Unloaded successfully
```

</details>

**Comment by jordanbriere** [comment]
Your server must have pulled the weapons data from #308, which requires this [fix](https://github.com/Source-Python-Dev-Team/Source.Python/commit/60571ba9494eac894fc213fe2a18667915499050) to be applied. The ideal solution would be to add the `grenade` filter to the [weapons](https://github.com/Source-Python-Dev-Team/Source.Python/blob/master/addons/source-python/data/source-python/weapons/tf.ini) that create projectile grenades but I don't know that game well enough to do so myself. PR welcome!

**Comment by ns-phennessy** [comment]
What qualifies as a grenade projectile? There are lots of projectiles in TF2; but grenades don't exist in Tf2 like they do in CSGO.

**Comment by jordanbriere** [comment]
Any weapon you would expect to be yielded when doing `for grenade in WeaponIter('grenade'):` qualifies as a grenade (same for `primary`, `secondary`, etc. that are tagged for other games). Though if you wouldn't expect any grenades on that game, then there is none to add.

However, the grenades are currently being used to determine whether the `inflictor` must be set into [Entity.take_damage](https://github.com/Source-Python-Dev-Team/Source.Python/blob/4c97b94b81e4631517b35777e01c6df58e320582/addons/source-python/packages/source-python/entities/_base.py#L1081-L1085) or not. Perhaps there is damage sources on that game that would requires that also. If that is the case and such weapons fit into other categories, then we could certainly map those as such and use per-engine/game filters to determine such cases.

Another thing to consider would be whether or not the engine dictate what is labeled as a grenade via the `FL_GRENADE` flags. If the engine handles some entities as grenade internally, then they would fit into that category for filtering.
