### ISSUE TITLE
CS:S VGUIMenu (Crash) > UserMessageBegin: New message started before matching call to EndMessage.

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#315]
Hello,

My server crashes when sending VGUIMenu. I'm getting a new window with: "UserMessageBegin: New message started before matching call to EndMessage."

Code to reproduce:

```
from messages import VGUIMenu

def get_motd(name, url, show=True):
    subkeys = dict()
    subkeys['title'] = name
    subkeys['type'] = 2
    subkeys['msg'] = url

    return VGUIMenu('info', subkeys=subkeys, show=show)
get_motd('Google', 'google.com').send()
```

gives me:

```
[SP] Loading plugin 'test'...

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\plugins\command.py", line 162, in load_plugin
    plugin = self.manager.load(plugin_name)
  File "..\addons\source-python\packages\source-python\plugins\manager.py", line 194, in load
    plugin._load()
  File "..\addons\source-python\packages\source-python\plugins\instance.py", line 74, in _load
    self.module = import_module(self.import_name)
  File "..\addons\source-python\plugins\test\test.py", line 10, in <module>
    get_motd('Google', 'google.com').send()
  File "..\addons\source-python\packages\source-python\messages\base.py", line 79, in send
    self._send(indexes, translated_kwargs)
  File "..\addons\source-python\packages\source-python\messages\base.py", line 95, in _send
    self.bitbuf(user_message.buffer, translated_kwargs)
  File "..\addons\source-python\packages\source-python\messages\base.py", line 191, in bitbuf
    buffer.write_string(value)

Boost.Python.ArgumentError: Python argument types in
    BitBufferWrite.write_string(BitBufferWrite, int)
did not match C++ signature:
    write_string(class bf_write {lvalue}, char const *)


[SP] Plugin 'test' was unable to be loaded.
```

and crashes with following message in window: "UserMessageBegin: New message started before matching call to EndMessage."

**Comment by Ayuto** [comment]
All subkeys and their values must be passed as strings. So, the issue is caused by your ``type`` subkey. I think we should enhance our code a little bit more to ensure all values have the proper types before actually creating the message.

**Comment by Frag1337** [comment]
Yep, the type was fault. Thanks

**Comment by Ayuto** [comment]
Okay, let's keep this open as a reminder for a potential enhancement.
