### ISSUE TITLE
Crash occurs when updating SP data (TF2 Linux)

### ISSUE THREAD

**Issue by jsza** [Source-Python-Dev-Team/Source.Python#347]
```
sp info

IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 22ca543f0f6558a26cbd12d129235ab4
Date          : 2020-08-20 18:29:52.342905
OS            : Linux-5.7.0-2-amd64-x86_64-with-debian-bullseye-sid
Game          : tf2
SP version    : 700
Github commit : 53f3bb562a2975c828d4c5145e21979859f57731
Server plugins:
   00: Source.Python, (C) 2012-2020, Source.Python Team.
SP plugins:
--------------------------------------------------------
```

As far as I could narrow it down, SRCDS crashes when extracting data:

```
[Source.Python] Loading...                                                                               
Setting up exception hooks...                                                                            
Setting up data update...                                                                                
Checking for data updates...                                                                                                                                                                                       
New data is available. Downloading...                                                                                                                                                                              
Downloading file (http://data.sourcepython.com/source-python-data.zip) to /home/jayess/srcds/tf2_testing/tf/addons/source-python/data/source-python-data.zip ...                                                   
File has been downloaded. Time elapsed: 1.19 seconds                                                     
Removing /home/jayess/srcds/tf2_testing/tf/addons/source-python/data/source-python ...                                                                                                                             
Extracting data in /home/jayess/srcds/tf2_testing/tf/addons/source-python/data ...                                                                                                                                 
free(): invalid pointer                                                                                                                                                                                            
Aborted (core dumped)                                                                                    
email debug.log to linux@valvesoftware.com
```

As the extraction was interrupted, SP is now missing most of its data and it doesn't attempt to update the data again.

I was unable to reproduce this on CS:S dedicated server, and I didn't test on any others. The crash always occurs on initial startup after installing SP, and subsequently if you delete `addons/source-python/data/source-python-data.zip`.

`debug.log` output:
```----------------------------------------------
CRASH: Thu 20 Aug 2020 16:48:39 SAST
Start Line: ./srcds_linux -game tf -maxplayers 20 +port 27015 -debug +map itemtest
[New LWP 1032984]
[New LWP 1032988]
[New LWP 1032986]
[New LWP 1032985]
[New LWP 1033041]
[New LWP 1033042]
[New LWP 1033040]
[New LWP 1033039]
[New LWP 1032987]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
Core was generated by `./srcds_linux -game tf -maxplayers 20 +port 27015 -debug +map itemtest'.
Program terminated with signal SIGABRT, Aborted.
#0  0xf7fb5179 in __kernel_vsyscall ()
[Current thread is 1 (Thread 0xf7fafac0 (LWP 1032984))]
#0  0xf7fb5179 in __kernel_vsyscall ()
#1  0xf7da1e32 in __libc_signal_restore_set (set=0xffa4176c) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
#2  __GI_raise (sig=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xf7d8a306 in __GI_abort () at abort.c:79
#4  0xf7de59cc in __libc_message (action=<optimized out>, fmt=<optimized out>) at ../sysdeps/posix/libc_fatal.c:155
#5  0xf7deda8d in malloc_printerr (str=str@entry=0xefc67222 "") at malloc.c:5347
#6  0xf7deec0f in _int_free (av=0xffffffff, p=0xe8efe60, have_lock=have_lock@entry=0) at malloc.c:4173
#7  0xf7df26c0 in __GI___libc_free (mem=mem@entry=0xe8efe68) at malloc.c:3125
#8  0xeb85ce2b in _PyMem_RawFree (ctx=0x0, ptr=0xe8efe68) at Objects/obmalloc.c:101
#9  0xeb85e4e6 in PyMem_RawFree (ptr=ptr@entry=0xe8efe68) at Objects/obmalloc.c:409
#10 0xebd0f2db in PyZlib_Free (ctx=0x0, ptr=0xe8efe68) at /home/ayuto/Desktop/Python-3.6.1/Modules/zlibmodule.c:139
#11 0xecc5d3e6 in inflateReset2 () from /home/jayess/srcds/tf2_testing/bin/replay_srv.so
#12 0xec74e49b in inflateInit2_ () from /lib/i386-linux-gnu/libz.so.1
#13 0xebd0fa86 in zlib_decompressobj_impl (module=0xea7ace3c, zdict=<optimized out>, wbits=-15) at /home/ayuto/Desktop/Python-3.6.1/Modules/zlibmodule.c:580
#14 zlib_decompressobj (module=module@entry=0xea7ace3c, args=args@entry=0xea2239e4, nargs=nargs@entry=1, kwnames=0x0) at /home/ayuto/Desktop/Python-3.6.1/Modules/clinic/zlibmodule.c.h:187
#15 0xeb857ee1 in _PyCFunction_FastCallDict (func_obj=func_obj@entry=0xea930144, args=args@entry=0xea2239e4, nargs=nargs@entry=1, kwargs=kwargs@entry=0x0) at Objects/methodobject.c:251
#16 0xeb85834c in _PyCFunction_FastCallKeywords (func=func@entry=0xea930144, stack=stack@entry=0xea2239e4, nargs=1, kwnames=kwnames@entry=0x0) at Objects/methodobject.c:295
#17 0xeb8e7afc in call_function (pp_stack=pp_stack@entry=0xffa41dbc, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4798
#18 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea22389c, throwflag=0) at Python/ceval.c:3284
#19 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea22389c, throwflag=throwflag@entry=0) at Python/ceval.c:718
#20 0xeb8e6d7d in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=0xea061464) at Python/ceval.c:4880
#21 0xeb8e7c91 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=0xea221b94, func=0xea082974) at Python/ceval.c:4915
#22 call_function (pp_stack=pp_stack@entry=0xffa41f5c, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#23 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea221a3c, throwflag=0) at Python/ceval.c:3284
#24 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea221a3c, throwflag=throwflag@entry=0) at Python/ceval.c:718
#25 0xeb8e7683 in _PyEval_EvalCodeWithName (_co=_co@entry=0xea066ee8, globals=globals@entry=0xea061464, locals=locals@entry=0x0, args=args@entry=0xffa42100, argcount=argcount@entry=6, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0x4, kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=0xea072358, defcount=2, kwdefs=kwdefs@entry=0x0, closure=0x0, name=name@entry=0xebd2f228, qualname=qualname@entry=0xea074290) at Python/ceval.c:4128
#26 0xeb8efbdb in _PyFunction_FastCallDict (func=func@entry=0xea082c44, args=args@entry=0xffa42100, nargs=nargs@entry=6, kwargs=kwargs@entry=0x0) at Python/ceval.c:5031
#27 0xeb7fd29c in _PyObject_FastCallDict (func=func@entry=0xea082c44, args=args@entry=0xffa42100, nargs=nargs@entry=6, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2295
#28 0xeb7fd3be in _PyObject_Call_Prepend (func=0xea082c44, obj=0xea06808c, args=args@entry=0xea069bcc, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2358
#29 0xeb814789 in method_call (method=0xea28a16c, args=0xea069bcc, kwargs=0x0) at Objects/classobject.c:317
#30 0xeb7fd046 in PyObject_Call (func=func@entry=0xea28a16c, args=args@entry=0xea069bcc, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2246
#31 0xeb878167 in slot_tp_init (self=0xea06808c, args=0xea069bcc, kwds=0x0) at Objects/typeobject.c:6380
#32 0xeb8709e6 in type_call (type=<optimized out>, type@entry=0xea085b0c, args=args@entry=0xea069bcc, kwds=kwds@entry=0x0) at Objects/typeobject.c:915
#33 0xeb7fd1ac in _PyObject_FastCallDict (func=func@entry=0xea085b0c, args=args@entry=0xea05a36c, nargs=nargs@entry=5, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2316
#34 0xeb7fd69c in _PyObject_FastCallKeywords (func=func@entry=0xea085b0c, stack=stack@entry=0xea05a36c, nargs=5, kwnames=kwnames@entry=0x0) at Objects/abstract.c:2480
#35 0xeb8e781a in call_function (pp_stack=pp_stack@entry=0xffa4235c, oparg=oparg@entry=5, kwnames=kwnames@entry=0x0) at Python/ceval.c:4822
#36 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea05a1ec, throwflag=0) at Python/ceval.c:3284
#37 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea05a1ec, throwflag=throwflag@entry=0) at Python/ceval.c:718
#38 0xeb8e7683 in _PyEval_EvalCodeWithName (_co=_co@entry=0xea075b78, globals=globals@entry=0xea061464, locals=locals@entry=0x0, args=args@entry=0xea21d344, argcount=argcount@entry=2, kwnames=kwnames@entry=0xea0796b8, kwargs=kwargs@entry=0xea21d34c, kwcount=kwcount@entry=1, kwstep=kwstep@entry=1, defs=defs@entry=0xea079c18, defcount=defcount@entry=2, kwdefs=kwdefs@entry=0xea0762fc, closure=closure@entry=0x0, name=name@entry=0xeab1fa40, qualname=qualname@entry=0xea076610) at Python/ceval.c:4128
#39 0xeb8e79db in fast_function (kwnames=0xea0796ac, nargs=2, stack=<optimized out>, func=0xea2076a4) at Python/ceval.c:4939
#40 call_function (pp_stack=pp_stack@entry=0xffa42530, oparg=oparg@entry=2, kwnames=kwnames@entry=0xea0796ac) at Python/ceval.c:4819
#41 0xeb8ebe10 in _PyEval_EvalFrameDefault (f=0xea21d1e4, throwflag=0) at Python/ceval.c:3300
#42 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea21d1e4, throwflag=throwflag@entry=0) at Python/ceval.c:718
#43 0xeb8e7683 in _PyEval_EvalCodeWithName (_co=_co@entry=0xea071ac8, globals=globals@entry=0xea061464, locals=locals@entry=0x0, args=args@entry=0xea2218a8, argcount=argcount@entry=4, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0xea2218b8, kwcount=kwcount@entry=0, kwstep=kwstep@entry=1, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0xe9ee1930, qualname=qualname@entry=0xea074a70) at Python/ceval.c:4128
#44 0xeb8e79db in fast_function (kwnames=0x0, nargs=4, stack=<optimized out>, func=0xea20780c) at Python/ceval.c:4939
#45 call_function (pp_stack=pp_stack@entry=0xffa426fc, oparg=oparg@entry=3, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#46 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea22175c, throwflag=0) at Python/ceval.c:3284
#47 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea22175c, throwflag=throwflag@entry=0) at Python/ceval.c:718
#48 0xeb8e7683 in _PyEval_EvalCodeWithName (_co=_co@entry=0xea0756a8, globals=globals@entry=0xea061464, locals=locals@entry=0x0, args=args@entry=0xea21e470, argcount=argcount@entry=4, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0xea21e480, kwcount=kwcount@entry=0, kwstep=kwstep@entry=1, defs=defs@entry=0xea079ef8, defcount=defcount@entry=2, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0xea75b6c0, qualname=qualname@entry=0xea076660) at Python/ceval.c:4128
#49 0xeb8e79db in fast_function (kwnames=0x0, nargs=4, stack=<optimized out>, func=0xea207734) at Python/ceval.c:4939
#50 call_function (pp_stack=pp_stack@entry=0xffa428cc, oparg=oparg@entry=3, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#51 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea21e31c, throwflag=0) at Python/ceval.c:3284
#52 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea21e31c, throwflag=throwflag@entry=0) at Python/ceval.c:718
#53 0xeb8e7683 in _PyEval_EvalCodeWithName (_co=_co@entry=0xea075c28, globals=globals@entry=0xea061464, locals=locals@entry=0x0, args=args@entry=0xe931e00, argcount=argcount@entry=2, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0xe931e08, kwcount=kwcount@entry=0, kwstep=kwstep@entry=1, defs=defs@entry=0xea076858, defcount=defcount@entry=3, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0xea9300c0, qualname=qualname@entry=0xea074980) at Python/ceval.c:4128
#54 0xeb8e79db in fast_function (kwnames=0x0, nargs=2, stack=<optimized out>, func=0xea20777c) at Python/ceval.c:4939
#55 call_function (pp_stack=pp_stack@entry=0xffa42a9c, oparg=oparg@entry=1, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#56 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xe931cbc, throwflag=0) at Python/ceval.c:3284
#57 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xe931cbc, throwflag=throwflag@entry=0) at Python/ceval.c:718
#58 0xeb8e6d7d in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=0, globals=0xea04fa54) at Python/ceval.c:4880
#59 0xeb8e7c91 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=0xea120b30, func=0xea207e84) at Python/ceval.c:4915
#60 call_function (pp_stack=pp_stack@entry=0xffa42c3c, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#61 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea1209ec, throwflag=0) at Python/ceval.c:3284
#62 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea1209ec, throwflag=throwflag@entry=0) at Python/ceval.c:718
#63 0xeb8e6d7d in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=1, globals=0xea04fa54) at Python/ceval.c:4880
#64 0xeb8e7cb7 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=0xea068358, func=0xea207d64) at Python/ceval.c:4922
#65 call_function (pp_stack=pp_stack@entry=0xffa42ddc, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#66 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xea06033c, throwflag=0) at Python/ceval.c:3284
#67 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xea06033c, throwflag=throwflag@entry=0) at Python/ceval.c:718
#68 0xeb8e6d7d in _PyFunction_FastCall (co=<optimized out>, args=<optimized out>, nargs=0, globals=0xea98eb1c) at Python/ceval.c:4880
#69 0xeb8e7c91 in fast_function (kwnames=0x0, nargs=<optimized out>, stack=0xeaa4d30c, func=0xea85c2fc) at Python/ceval.c:4915
#70 call_function (pp_stack=pp_stack@entry=0xffa42f7c, oparg=oparg@entry=0, kwnames=kwnames@entry=0x0) at Python/ceval.c:4819
#71 0xeb8eb9e3 in _PyEval_EvalFrameDefault (f=0xeaa4d1cc, throwflag=0) at Python/ceval.c:3284
#72 0xeb8e6cbc in PyEval_EvalFrameEx (f=f@entry=0xeaa4d1cc, throwflag=throwflag@entry=0) at Python/ceval.c:718
#73 0xeb8e7683 in _PyEval_EvalCodeWithName (_co=_co@entry=0xea987cd8, globals=globals@entry=0xea98eb1c, locals=locals@entry=0x0, args=args@entry=0xebd30038, argcount=argcount@entry=0, kwnames=kwnames@entry=0x0, kwargs=kwargs@entry=0x4, kwcount=kwcount@entry=0, kwstep=kwstep@entry=2, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=kwdefs@entry=0x0, closure=closure@entry=0x0, name=name@entry=0x0, qualname=qualname@entry=0x0) at Python/ceval.c:4128
#74 0xeb8e7d56 in PyEval_EvalCodeEx (_co=0xea987cd8, globals=0xea98eb1c, locals=locals@entry=0x0, args=args@entry=0xebd30038, argcount=0, kws=kws@entry=0x0, kwcount=kwcount@entry=0, defs=defs@entry=0x0, defcount=defcount@entry=0, kwdefs=0x0, closure=0x0) at Python/ceval.c:4149
#75 0xeb83175d in function_call (func=0xeaa32fa4, arg=0xebd3002c, kw=0x0) at Objects/funcobject.c:604
#76 0xeb7fd046 in PyObject_Call (func=func@entry=0xeaa32fa4, args=args@entry=0xebd3002c, kwargs=kwargs@entry=0x0) at Objects/abstract.c:2246
#77 0xeb8e8279 in PyEval_CallObjectWithKeywords (func=func@entry=0xeaa32fa4, args=args@entry=0xebd3002c, kwargs=kwargs@entry=0x0) at Python/ceval.c:4718
#78 0xeb914672 in PyEval_CallFunction (obj=0xeaa32fa4, format=0xeb56aad9 "()") at Python/modsupport.c:504
#79 0xeb06ccb5 in CPythonManager::Initialize() () from /home/jayess/srcds/tf2_testing/tf/addons/source-python/bin/core.so
#80 0xeb07007b in CSourcePython::Load(void* (*)(char const*, int*), void* (*)(char const*, int*)) () from /home/jayess/srcds/tf2_testing/tf/addons/source-python/bin/core.so
#81 0xecbcd8bb in CSourcePython::Load(void* (*)(char const*, int*), void* (*)(char const*, int*)) () from /home/jayess/srcds/tf2_testing/tf/addons/source-python.so
#82 0xf661b910 in CPlugin::Load(char const*) () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#83 0xf661c087 in CServerPlugin::LoadPlugin(char const*) () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#84 0xf661c29b in CServerPlugin::LoadPlugins() () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#85 0xf6612ac5 in SV_InitGameDLL() () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#86 0xf659ef15 in Host_Init(bool) () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#87 0xf6629518 in Sys_InitGame(void* (*)(char const*, int*), char const*, void*, int) () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#88 0xf662cc2e in CEngine::Load(bool, char const*) () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#89 0xf662a9ee in CModAppSystemGroup::Main() () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#90 0xf6674e08 in CAppSystemGroup::Run() () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#91 0xf662b74d in CDedicatedServerAPI::ModInit(ModInfo_t&) () from /home/jayess/srcds/tf2_testing/bin/engine_srv.so
#92 0xf7384093 in CDedicatedAppSystemGroup::Main() () from bin/dedicated_srv.so
#93 0xf7466a78 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#94 0xf7466a78 in CAppSystemGroup::Run() () from bin/dedicated_srv.so
#95 0xf733e748 in main () from bin/dedicated_srv.so
#96 0x080489cb in main ()
No symbol table info available.
eax            0x0                 0
ecx            0xffa4176c          -6023316
edx            0x0                 0
ebx            0x2                 2
esp            0xffa41750          0xffa41750
ebp            0xffa4176c          0xffa4176c
esi            0x8                 8
edi            0x0                 0
eip            0xf7fb5179          0xf7fb5179 <__kernel_vsyscall+9>
eflags         0x200282            [ SF IF ID ]
cs             0x23                35
ss             0x2b                43
ds             0x2b                43
es             0x2b                43
fs             0x0                 0
gs             0x63                99
From        To          Syms Read   Shared Object Library
0xf7f79130  0xf7f7a304  Yes         /lib/i386-linux-gnu/libdl.so.2
0xf7f5c5b0  0xf7f6c8b4  Yes         /lib/i386-linux-gnu/libpthread.so.0
0xf7d8a0f0  0xf7eddac6  Yes         /lib/i386-linux-gnu/libc.so.6
0xf7fb7090  0xf7fd3993  Yes         /lib/ld-linux.so.2
0xf7d43c40  0xf7d59cd8  Yes (*)     bin/libtier0_srv.so
0xf7d303d0  0xf7d33fa4  Yes         /lib/i386-linux-gnu/librt.so.1
0xf7bdc130  0xf7cc4095  Yes (*)     /usr/lib/i386-linux-gnu/libstdc++.so.6
0xf7a6b190  0xf7b2b511  Yes         /lib/i386-linux-gnu/libm.so.6
0xf7a42300  0xf7a57985  Yes (*)     /lib/i386-linux-gnu/libgcc_s.so.1
0xf79422a0  0xf79751b8  Yes (*)     bin/libvstdlib_srv.so
0xf733d8a0  0xf7488a64  Yes (*)     bin/dedicated_srv.so
0xf72a1fd0  0xf72d1a04  Yes (*)     bin/libsteam_api.so
0xf716d6c0  0xf7179c94  Yes (*)     /lib/i386-linux-gnu/libtinfo.so.5
0xf64e3250  0xf66a06c8  Yes (*)     /home/jayess/srcds/tf2_testing/bin/engine_srv.so
0xf6928570  0xf6950ed4  Yes (*)     /home/jayess/srcds/tf2_testing/bin/soundemittersystem_srv.so
0xf5eee7c0  0xf5fca7a4  Yes (*)     /home/jayess/srcds/tf2_testing/bin/materialsystem_srv.so
0xf38b09c0  0xf39611d4  Yes (*)     /home/jayess/srcds/tf2_testing/bin/studiorender_srv.so
0xf356f140  0xf36900c4  Yes (*)     /home/jayess/srcds/tf2_testing/bin/vphysics_srv.so
0xf3e14d90  0xf3e61f64  Yes (*)     /home/jayess/srcds/tf2_testing/bin/datacache_srv.so
0xf7f843e0  0xf7f9c264  Yes (*)     /home/jayess/srcds/tf2_testing/bin/shaderapiempty_srv.so
0xf0d6e4a0  0xf1a72024  Yes (*)     /home/jayess/srcds/tf2_testing/tf/bin/server_srv.so
0xf3806590  0xf3820f64  Yes (*)     /home/jayess/srcds/tf2_testing/bin/scenefilecache_srv.so
0xecbffdb0  0xecc663d4  Yes (*)     /home/jayess/srcds/tf2_testing/bin/replay_srv.so
0xecb24770  0xecb86754  Yes (*)     /usr/lib/i386-linux-gnu/libcurl-gnutls.so.4
0xecaf12c0  0xecb06a94  Yes (*)     /usr/lib/i386-linux-gnu/libnghttp2.so.14
0xecacc2f0  0xecad0204  Yes (*)     /usr/lib/i386-linux-gnu/libidn2.so.0
0xecaadb60  0xecabcd64  Yes (*)     /usr/lib/i386-linux-gnu/librtmp.so.1
0xeca78660  0xeca95e34  Yes (*)     /usr/lib/i386-linux-gnu/libssh2.so.1
0xeca64250  0xeca65d74  Yes (*)     /usr/lib/i386-linux-gnu/libpsl.so.5
0xeca27ae0  0xeca4b244  Yes (*)     /usr/lib/i386-linux-gnu/libnettle.so.8
0xec854880  0xec965a54  Yes (*)     /usr/lib/i386-linux-gnu/libgnutls.so.30
0xec7e53c0  0xec816744  Yes (*)     /usr/lib/i386-linux-gnu/libgssapi_krb5.so.2
0xec78df10  0xec7bed94  Yes (*)     /usr/lib/i386-linux-gnu/libldap_r-2.4.so.2
0xec774670  0xec77af74  Yes (*)     /usr/lib/i386-linux-gnu/liblber-2.4.so.2
0xec7630e0  0xec76a154  Yes (*)     /usr/lib/i386-linux-gnu/libbrotlidec.so.1
0xec747310  0xec757de9  Yes (*)     /lib/i386-linux-gnu/libz.so.1
0xec5cf0c0  0xec604454  Yes (*)     /usr/lib/i386-linux-gnu/libunistring.so.2
0xec580ec0  0xec5915e4  Yes (*)     /usr/lib/i386-linux-gnu/libhogweed.so.6
0xec4f7380  0xec558324  Yes (*)     /usr/lib/i386-linux-gnu/libgmp.so.10
0xec40e550  0xec495174  Yes (*)     /usr/lib/i386-linux-gnu/libgcrypt.so.20
0xec2c7890  0xec36b954  Yes (*)     /usr/lib/i386-linux-gnu/libp11-kit.so.0
0xec2a23a0  0xec2ae554  Yes (*)     /usr/lib/i386-linux-gnu/libtasn1.so.6
0xec1d3940  0xec235b84  Yes (*)     /usr/lib/i386-linux-gnu/libkrb5.so.3
0xec18c580  0xec1a9104  Yes (*)     /usr/lib/i386-linux-gnu/libk5crypto.so.3
0xec1842b0  0xec185024  Yes (*)     /lib/i386-linux-gnu/libcom_err.so.2
0xec176640  0xec17cbb4  Yes (*)     /usr/lib/i386-linux-gnu/libkrb5support.so.0
0xec15e3b0  0xec16ac64  Yes         /lib/i386-linux-gnu/libresolv.so.2
0xec13e5b0  0xec14f414  Yes (*)     /usr/lib/i386-linux-gnu/libsasl2.so.2
0xec11a040  0xec11a3a6  Yes (*)     /usr/lib/i386-linux-gnu/libbrotlicommon.so.1
0xec0f46a0  0xec108784  Yes (*)     /lib/i386-linux-gnu/libgpg-error.so.0
0xec0e8250  0xec0ec8b4  Yes (*)     /usr/lib/i386-linux-gnu/libffi.so.7
0xec0e1270  0xec0e25d4  Yes (*)     /lib/i386-linux-gnu/libkeyutils.so.1
0xecbccbc0  0xecbe3cd4  Yes (*)     /home/jayess/srcds/tf2_testing/tf/addons/source-python.so
0xeb7ec040  0xeba87fa4  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/plat-linux/libpython3.6m.so.1.0
0xebd6f210  0xebd6fce4  Yes         /lib/i386-linux-gnu/libutil.so.1
0xeb05adb0  0xeb4c3ab4  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/bin/core.so
0xebd97750  0xebd985ce  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_heapq.cpython-36m-i386-linux-gnu.so
0xebd89970  0xebd91e04  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/math.cpython-36m-i386-linux-gnu.so
0xebd18350  0xebd26434  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_datetime.cpython-36m-i386-linux-gnu.so
0xebd83990  0xebd84c04  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_md5.cpython-36m-i386-linux-gnu.so
0xebd7f990  0xebd80a84  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_sha1.cpython-36m-i386-linux-gnu.so
0xebd799f0  0xebd7ca34  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_sha256.cpython-36m-i386-linux-gnu.so
0xea83b9f0  0xea8449b4  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_sha512.cpython-36m-i386-linux-gnu.so
0xea82d270  0xea837d24  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_blake2.cpython-36m-i386-linux-gnu.so
0xea823760  0xea829104  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_sha3.cpython-36m-i386-linux-gnu.so
0xf3e00610  0xf3e0085a  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_opcode.cpython-36m-i386-linux-gnu.so
0xebd0f190  0xebd11fb8  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/zlib.cpython-36m-i386-linux-gnu.so
0xebd74ea0  0xebd76392  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_bz2.cpython-36m-i386-linux-gnu.so
0xea7e02b0  0xea7ecc94  Yes (*)     /lib/i386-linux-gnu/libbz2.so.1.0
0xea81a660  0xea81dbc1  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_lzma.cpython-36m-i386-linux-gnu.so
0xea6ed510  0xea706724  Yes (*)     /lib/i386-linux-gnu/liblzma.so.5
0xea815b10  0xea8161c2  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/grp.cpython-36m-i386-linux-gnu.so
0xea8117d0  0xea81200a  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_bisect.cpython-36m-i386-linux-gnu.so
0xea80dc30  0xea80e8b1  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_random.cpython-36m-i386-linux-gnu.so
0xea808e40  0xea809f34  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_posixsubprocess.cpython-36m-i386-linux-gnu.so
0xea802420  0xea8044ed  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/select.cpython-36m-i386-linux-gnu.so
0xea7f79e0  0xea7fbed2  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_struct.cpython-36m-i386-linux-gnu.so
0xea7d8de0  0xea7db1e4  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/binascii.cpython-36m-i386-linux-gnu.so
0xea72e8b0  0xea73c804  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_socket.cpython-36m-i386-linux-gnu.so
0xea721440  0xea72791e  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_json.cpython-36m-i386-linux-gnu.so
0xea694bc0  0xea6a33a4  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_pickle.cpython-36m-i386-linux-gnu.so
0xea37c3c0  0xea3b2b54  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/_decimal.cpython-36m-i386-linux-gnu.so
0xe9dee3a0  0xe9df1114  Yes         /home/jayess/srcds/tf2_testing/tf/addons/source-python/Python3/lib-dynload/unicodedata.cpython-36m-i386-linux-gnu.so
0xea035300  0xea03b8c4  Yes         /lib/i386-linux-gnu/libnss_files.so.2
0xea71a1c0  0xea71cec4  Yes         /lib/i386-linux-gnu/libnss_dns.so.2
(*): Shared library is missing debugging information.
Dump of assembler code for function __kernel_vsyscall:
   0xf7fb5170 <+0>:	push   %ecx
   0xf7fb5171 <+1>:	push   %edx
   0xf7fb5172 <+2>:	push   %ebp
   0xf7fb5173 <+3>:	mov    %esp,%ebp
   0xf7fb5175 <+5>:	sysenter 
   0xf7fb5177 <+7>:	int    $0x80
=> 0xf7fb5179 <+9>:	pop    %ebp
   0xf7fb517a <+10>:	pop    %edx
   0xf7fb517b <+11>:	pop    %ecx
   0xf7fb517c <+12>:	ret    
End of assembler dump.
Stack level 0, frame at 0xffa41760:
 eip = 0xf7fb5179 in __kernel_vsyscall; saved eip = 0xf7da1e32
 called by frame at 0xffa41890
 Arglist at 0xffa41758, args: 
 Locals at 0xffa41758, Previous frame's sp is 0xffa41760
 Saved registers:
  ecx at 0xffa41758, edx at 0xffa41754, ebp at 0xffa41750, eip at 0xffa4175c
End of Source crash report
----------------------------------------------```

**Comment by Ayuto** [comment]
Sounds like a permission or insufficient memory problem to me. I just did a fresh installation and tried to reproduce it, but I'm unable to do so.

Could you please check the memory and permissions?
