### ISSUE TITLE
Debian 10 64bit SP installation errors?

### ISSUE THREAD

**Issue by ae2xdnk** [Source-Python-Dev-Team/Source.Python#377]
Hi i tryed install on debian 10 64bit server sourcepython but i get these errors:
```
File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/__init__.py", line 77, in <module>
from loggers import _sp_logger # It's save to import this here

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/loggers.py", line 408, in <module>
'%Y-%m-%d %H:%M:%S')

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/loggers.py", line 373, in __init__
self._handler = FileHandler(log_path, encoding=encoding)

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/Python3/logging/__init__.py", line 1030, in __init__
StreamHandler.__init__(self, self._open())

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/Python3/logging/__init__.py", line 1059, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding) 

PermissionError: [Errno 13] Permission denied: '/var/lib/puservers/ff19a6aa/cstrike/logs/source-python/source-python.2021-01-02.log'
[Source.Python] Unloaded successfully.
```
Any help?

**Comment by ae2xdnk** [comment]
here is full error..


[Source.Python] Loading...
[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/__init__.py", line 77, in <module>
from loggers import _sp_logger # It's save to import this here

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/loggers.py", line 408, in <module>
'%Y-%m-%d %H:%M:%S')

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/loggers.py", line 373, in __init__
self._handler = FileHandler(log_path, encoding=encoding)

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/Python3/logging/__init__.py", line 1030, in __init__
StreamHandler.__init__(self, self._open())

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/Python3/logging/__init__.py", line 1059, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)

PermissionError: [Errno 13] Permission denied: '/var/lib/puservers/ff19a6aa/cstrike/logs/source-python/source-python.2021-01-02.log'
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Failed to unload the main module.
Traceback (most recent call last):

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/__init__.py", line 77, in <module>
from loggers import _sp_logger # It's save to import this here

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/loggers.py", line 408, in <module>
'%Y-%m-%d %H:%M:%S')

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/packages/source-python/loggers.py", line 373, in __init__
self._handler = FileHandler(log_path, encoding=encoding)

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/Python3/logging/__init__.py", line 1030, in __init__
StreamHandler.__init__(self, self._open())

File "/var/lib/pufferpanel/servers/ff19a6aa/cstrike/addons/source-python/Python3/logging/__init__.py", line 1059, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding)

PermissionError: [Errno 13] Permission denied: '/var/lib/puservers/ff19a6aa/cstrike/logs/source-python/source-python.2021-01-02.log'
[Source.Python] Unloaded successfully.

**Comment by Ayuto** [comment]
Looks like the server doesn't has write permissions to the log directory.

**Comment by ae2xdnk** [comment]
should i chmod logs file?
