### ISSUE TITLE
[Source.Python] Failed

### ISSUE THREAD

**Issue by benoit611** [Source-Python-Dev-Team/Source.Python#418]
hello I have had a problem for several months after updating the new srcds update I became unable to use source-python I tried to download it from the site but it still doesn't work

i'm on windows 10 

Console initialized.
Using Breakpad minidump system. Version: 6630498 AppID: 232330
Loaded 1335 VPK file hashes from h:\srcds\srcds\multimod\cstrike\cstrike_pak.vpk for pure server operation.
Loaded 1335 VPK file hashes from h:\srcds\srcds\multimod\cstrike\cstrike_pak.vpk for pure server operation.
Loaded 1218 VPK file hashes from h:\srcds\srcds\multimod\hl2\hl2_textures.vpk for pure server operation.
Loaded 574 VPK file hashes from h:\srcds\srcds\multimod\hl2\hl2_sound_vo_english.vpk for pure server operation.
Loaded 383 VPK file hashes from h:\srcds\srcds\multimod\hl2\hl2_sound_misc.vpk for pure server operation.
Loaded 446 VPK file hashes from h:\srcds\srcds\multimod\hl2\hl2_misc.vpk for pure server operation.
Loaded 5 VPK file hashes from h:\srcds\srcds\multimod\platform\platform_misc.vpk for pure server operation.
server.dll loaded for "Counter-Strike: Source"
[Source.Python] Loading...

[SP] Avertissement rencontr├®:
  File '..\addons\source-python\packages\site-packages\mutagen\id3\_specs.py', line 666: DeprecationWarning
    invalid escape sequence \s

[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\site-packages\path.py", line 100, in io_error_compat
    yield

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\site-packages\path.py", line 743, in open
    return io.open(self, *args, **kwargs)

FileNotFoundError: [Errno 2] No such file or directory: Path('h:\\srcds\\srcds\\test\\cstrike\\cfg\\source-python\\auth\\players.json')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\__init__.py", line 94, in load
    setup_auth()

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\__init__.py", line 357, in setup_auth
    auth_manager.load()

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\auth\manager.py", line 295, in load
    self.set_active_backend(_core_settings['AUTH_SETTINGS']['backend'])

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\auth\manager.py", line 316, in set_active_backend
    backend.load()

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\auth\backends\flatfile.py", line 52, in load
    self.sync()

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\auth\backends\flatfile.py", line 59, in sync
    auth_manager.players, self.options['player_config_path'])

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\source-python\auth\backends\flatfile.py", line 122, in load_json_config
    with path.open('w') as file:

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\site-packages\path.py", line 743, in open
    return io.open(self, *args, **kwargs)

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\Python3\contextlib.py", line 100, in __exit__
    self.gen.throw(type, value, traceback)

  File "h:\srcds\srcds\multimod\cstrike\addons\source-python\packages\site-packages\path.py", line 106, in io_error_compat
    raise os_err

FileNotFoundError: [Errno 2] No such file or directory: Path('h:\\srcds\\srcds\\test\\cstrike\\cfg\\source-python\\auth\\players.json')
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Unloaded successfully.
Unknown command "sp"

**Comment by jordanbriere** [comment]
Open your `../cfg/source-python/core_settings.ini` file and update the `BACKENDS` paths. Your problem is that you moved your server to a different location (from `test` to `multimod`) and the former one no longer exists.

**Comment by benoit611** [comment]
jordanbriere thank you
