### ISSUE TITLE
new traceback error? 

### ISSUE THREAD

**Issue by Lolles1911** [Source-Python-Dev-Team/Source.Python#433]
hi, Tried this fix but get this error? #429 

[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\entities\hooks.py", line 225, in on_networked_entity_created
    _waiting_entity_hooks.initialize(entity.index)
  File "..\addons\source-python\packages\source-python\entities\hooks.py", line 212, in initialize
    if hook.initialize(entity):
  File "..\addons\source-python\packages\source-python\entities\hooks.py", line 162, in initialize
    self.hooked_function = getattr(entity, self.function)
  File "..\addons\source-python\packages\source-python\entities\_base.py", line 247, in __getattr__
    value = value.__get__(instance)
  File "..\addons\source-python\packages\source-python\memory\manager.py", line 664, in __get__
    func = binary[identifier].make_function(

ValueError: Could not find signature: 558bec83e4f883ec2c5356576a01

**Comment by CookStar** [comment]
#434
