### ISSUE TITLE
RuntimeError: CHECK failed: (to->GetDescriptor()) == (descriptor): Tried to merge messages of different types.

### ISSUE THREAD

**Issue by Phoross** [Source-Python-Dev-Team/Source.Python#451]
I'm using Source.Python to run a WCS server and everything was working fine yesterday but starting today I'm having an error popping up endlessly when I try to use the command 'wcs' which open a radio menu with all the options.
The error is the following one : 
`[libprotobuf FATAL ..\src\google\protobuf\reflection_ops.cc:58] CHECK failed: (to->GetDescriptor()) == (descriptor): Tried to merge messages of different types.
[Source.Python]
[SP] Caught an Exception:
Traceback (most recent call last):
  File "..\addons\source-python\packages\source-python\listeners\tick.py", line 79, in _tick
    self.pop(0).execute()
  File "..\addons\source-python\packages\source-python\listeners\tick.py", line 160, in execute
    return self.callback(*self.args, **self.kwargs)
  File "..\addons\source-python\plugins\wcs\wcs.py", line 372, in _send_message_and_remove
    message.send(wcsplayer.index, **kwargs)
  File "..\addons\source-python\packages\source-python\menus\base.py", line 174, in send
    queue._refresh()
  File "..\addons\source-python\packages\source-python\menus\queue.py", line 105, in _refresh
    menu._refresh(self._index)
  File "..\addons\source-python\packages\source-python\menus\base.py", line 104, in _refresh
    self._send(player_index)
  File "..\addons\source-python\packages\source-python\menus\radio.py", line 120, in _send
    ShowMenu(*self._build(player_index)).send(player_index)
  File "..\addons\source-python\packages\source-python\messages\base.py", line 232, in send
    user_message.send()

RuntimeError: CHECK failed: (to->GetDescriptor()) == (descriptor): Tried to merge messages of different types.`

It doesn't happen until I type the command in the chat and for then on it's non stop in the console.
A change in Source.Python that may be causing this? Don't know how to fix it :/

**Comment by Phoross** [comment]
Here is my output for `sp info` :
`sp info
[Source.Python]
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : df92d21fc1e74dc058c36de1cef0cf27
Date          : 2022-07-24 11:12:59.607624
OS            : Windows-10-10.0.19041
Game          : csgo
SP version    : 714
Github commit : d0ffd8ccbd1e9923c9bc44936f20613c1c76b7fb
Server plugins:
   00: Metamod:Source 1.11.0-dev+1148
   01: Source.Python, (C) 2012-2021, Source.Python Team.
SP plugins:
   00: es_emulator, https://github.com/Ayuto/EventScripts-Emulator
   01: wcs, 2022.02.22-1, https://forums.sourcepython.com/viewtopic.php?f=7&t=1925
   02: commandsx
--------------------------------------------------------`

I'll try and replace SourceMod with SourceMod 1.10 and see if that fixes it!

**Comment by Phoross** [comment]
Do I leave the issue open until there is a fix for 1.11 or is that not necessary?
