### ISSUE TITLE
messages - UnicodeDecodeError

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#452]
Hey,

I was just checking my logs and found this in here:

```
Client "ðŸ–¤ðŸ‡ºðŸ‡¦ÐœÐÐ¨ÐðŸ‡ºðŸ‡¦ðŸ–" connected (X.XXX.XXX.XXX:27005).
[Source.Python] 
[SP] Caught an Exception:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/messages/hooks.py", line 278, in _pre_message_end
    data = impl.read(buffer_read)
  File "../addons/source-python/packages/source-python/messages/impl.py", line 113, in read
    return cls.read_bitbuffer(buffer)
  File "../addons/source-python/packages/source-python/messages/impl.py", line 159, in read_bitbuffer
    param1=buffer.read_string(),

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 28-30: unexpected end of data
```

Is this sp related or something else?

**Comment by srpg** [comment]
> Hey,
> 
> I was just checking my logs and found this in here:
> 
> ```
> Client "ðŸ–¤ðŸ‡ºðŸ‡¦ÐœÐ�Ð¨Ð�ðŸ‡ºðŸ‡¦ðŸ–" connected (X.XXX.XXX.XXX:27005).
> [Source.Python] 
> [SP] Caught an Exception:
> Traceback (most recent call last):
>   File "../addons/source-python/packages/source-python/messages/hooks.py", line 278, in _pre_message_end
>     data = impl.read(buffer_read)
>   File "../addons/source-python/packages/source-python/messages/impl.py", line 113, in read
>     return cls.read_bitbuffer(buffer)
>   File "../addons/source-python/packages/source-python/messages/impl.py", line 159, in read_bitbuffer
>     param1=buffer.read_string(),
> 
> UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 28-30: unexpected end of data
> ```
> 
> Is this sp related or something else?

I think it is, i have been getting those errors sometimes aswell

**Comment by Ayuto** [comment]
Yes, this seems to be an issue with our user message hook.

**Comment by srpg** [comment]
> Yes, this seems to be an issue with our user message hook.
> 
> Which user message hooka are you using? The issue shouldn't occur if no SP plugin is loaded.
I use it only in:

@HookUserMessage('SayText2')
def _saytext2_hook(recipients, data):
	if data['index'] == 0:
		return True
	recipients.remove_all_players()

**Comment by Frag1337** [comment]
I'm also using SayText2 hook.

> > Yes, this seems to be an issue with our user message hook.
> > Which user message hooka are you using? The issue shouldn't occur if no SP plugin is loaded.
> 
> I use it only in:
> 
> @HookUserMessage('SayText2') def _saytext2_hook(recipients, data): if data['index'] == 0: return True recipients.remove_all_players()

I'm using SayText2 hook aswell.

**Comment by srpg** [comment]
Just tested the fix in my linux server, when i used that code, it still showed error.

[2022-08-26 13:47:08]: [SP] Loading plugin 'test'...
[2022-08-26 13:47:08]: Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processUnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 139: invalid continuation byte
[2022-08-26 13:47:08]: [Bots] Seth: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa�
[2022-08-26 13:47:08]: [SP] Successfully loaded plugin 'test`

**Comment by srpg** [comment]
I can confirm that the latest commit fixed the error
