### ISSUE TITLE
 Unable to load python, csgo

### ISSUE THREAD

**Issue by Lolles1911** [Source-Python-Dev-Team/Source.Python#453]
Hello.

Can someone tell me why it won't load source:python?

[Source.Python] Loading...
[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):
  File "/home/container/csgo/addons/source-python/packages/source-python/__init__.py", line 94, in load setup_sqlite()
  File "/home/container/csgo/addons/source-python/packages/source-python/__init__.py", line 468, in setup_sqlite import ctypes
  File "/home/container/csgo/addons/source-python/Python3/ctypes/__init__.py", line 7, in <module> from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Unloaded successfully

**Comment by srpg** [comment]
Hi, it seems its missing libffi.so.6
Here the link for [url=http://wiki.sourcepython.com/general/installation.html]install info[/url]

**Comment by Lolles1911** [comment]
thanks
