### ISSUE TITLE
Source.Python data mismatch for latest release

### ISSUE THREAD

**Issue by waldotf** [Source-Python-Dev-Team/Source.Python#486]
```
sp info
[Source.Python]
IMPORTANT: Please copy the full output.
--------------------------------------------------------
Checksum      : 1f454c49a6ac657e4b1905231092e2f6
Date          : 2023-07-08 00:10:24.392609
OS            : Linux-5.10.0-23-amd64-x86_64-with-debian-10.13
Game          : tf2
SP version    : 721
Github commit : f129713a17014795de445ff8fa782e079c76ef4e
Server plugins:
   00: Metamod:Source 1.11.0-dev+1148
   01: Source.Python, (C) 2012-2021, Source.Python Team.
SP plugins:
   00: tempus_loader
   01: noshake
--------------------------------------------------------
```

The data hosted at http://data.sourcepython.com/source-python-data.zip doesn't seem to match the [latest release,](https://github.com/Source-Python-Dev-Team/Source.Python/blob/f129713a17014795de445ff8fa782e079c76ef4e/addons/source-python/data/source-python/entities/orangebox/tf/CBaseEntity.ini) giving errors like this after automatic data updates:

```
Setting CBaseEntity to non-brush model models/props_junk/gascan001a.mdl
[Source.Python]
[SP]
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/entities/_base.py", line 244, in __getattr__
    instance, value = self.dynamic_attributes[attr]
KeyError: 'get_solid_mask'

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "../addons/source-python/packages/source-python/entities/_base.py", line 246, in __getattr__
    raise AttributeError('Attribute "{0}" not found'.format(attr))

AttributeError: Attribute "get_solid_mask" not found
```

**Comment by Ayuto** [comment]
Just regenerated the data. Could you please check again? Seems like the automatic generation didn't work the last time.

**Comment by waldotf** [comment]
Seems to still be the same old version.

**Comment by Ayuto** [comment]
Figured out the issue. Now it should be correct.

**Comment by waldotf** [comment]
Works now, thanks.
