### ISSUE TITLE
Menu KeyError

### ISSUE THREAD

**Issue by Frag1337** [Source-Python-Dev-Team/Source.Python#487]
Hi, my console is ocassionaly filled with these. Not sure how to reproduce that. Maybe it has something to do with sourcemod menu's clashing?

```py
Traceback (most recent call last):
  File "/home/cssserver1/serverfiles/cstrike/addons/source-python/packages/source-python/commands/auth.py", line 44, in __call__
    return self.callback(*args)
  File "/home/cssserver1/serverfiles/cstrike/addons/source-python/packages/source-python/menus/queue.py", line 267, in _menuselect_callback
    _radio_queues[index]._select(choice)
  File "/home/cssserver1/serverfiles/cstrike/addons/source-python/packages/source-python/menus/queue.py", line 126, in _select
    next_menu = active_menu._select(self._index, choice)
  File "/home/cssserver1/serverfiles/cstrike/addons/source-python/packages/source-python/menus/radio.py", line 113, in _select
    self._player_pages[player_index].options[choice_index])
KeyError: 3
```

**Comment by Ayuto** [comment]
Yes, this is likely a conflict with another server plugin. Could be difficult to fix.

**Comment by srpg** [comment]
I get those errors randomly aswell, even i thought i only have installed sp and only use sp plugins i made
