### ISSUE TITLE
Source-Python for Half-life 2 Deathmatch

### ISSUE THREAD

**Issue by Lunacy1984** [Source-Python-Dev-Team/Source.Python#500]
In regards to support for Half-life 2 Deathmatch.
As of November 17 2024 with the 20th anniversary update this plugin will no longer work on a half-life 2 deathmatch server. With no other plugins or addons installed Source-Python will cause the server to crash. A good number of severs need python to use addons.

**Comment by Ayuto** [comment]
Thanks for reporting! Unfortunately, I can't provide an official fix at the moment as I don't have access to our build system until the 2nd of December. I will then provide a fix.

**Comment by Lunacy1984** [comment]
Thankyou. I figured this would take some time. It will hopefully give Valve enough time to finish unexpected patches they seem to be putting out every other day. I am trying to rewrite some scrips for my server in the mean time with sourcemod.

**Comment by Lunacy1984** [comment]
That's what I was hoping for too is the Eventscripts. Brand New for 1979 still runs a great deal of visual effects with Eventscripts and Python. Largely obsolete, but I don't know how to write it for Sourcemod.

**Comment by Lunacy1984** [comment]
> Great news, thank you for that commitment to fix SP for HL2DM. Can you please investigate the impact on your EventScripts Emulator too. I am assuming it is not working given Matties EventScripts is currently broken.

That's what I was hoping for too is the Eventscripts. Brand New for 1979 still runs a great deal of visual effects with Eventscripts and Python. Largely obsolete, but I don't know how to write it for Sourcemod.

**Comment by Lunacy1984** [comment]
Any update?

**Comment by Lunacy1984** [comment]
Any update

**Comment by Lunacy1984** [comment]
Any update so far or just trying to make sense of the valve updates?

**Comment by LsLoki** [comment]
Why is this closed?

**Comment by Lunacy1984** [comment]
Replying to someone else's comment caused it to close. This is NOT closed.

**Comment by Lunacy1984** [comment]
User interface issue. NOT CLOSED by any means

**Comment by Ayuto** [comment]
Sorry for the delay. It has been a busy week. A new build is now available. Though, HL2DM requires new signatures on Windows. This is still an open ToDo.

**Comment by Lunacy1984** [comment]
I hear you. I have hardly had time for my server stuff with the push for the holidays.

**Comment by Lunacy1984** [comment]
We still have a problem or missing file. unzipped and placed the pack in hl2mp. and got this in the console.
[Source.Python] Loading...
=========================================================================
[SP-LOADER] Could not load library: bin/core.dll
[SP-LOADER] (Code: 126) The specified module could not be found.
=========================================================================
Failed to load plugin "addons/source-python"

Bin folder is empty aside from the readme. Am I missing a step?

**Comment by Lunacy1984** [comment]
So not ready for HL2DM yet. Thought I saw quick fix for hl2dm.

**Comment by Ayuto** [comment]
Linux should be fine. Windows will crash unless you disable the entities listener.

**Comment by Lunacy1984** [comment]
I deleted a comment since I saw my own error

**Comment by LsLoki** [comment]
> Linux should be fine. Windows will crash unless you disable the entities listener.

Can you please update this thread when you have updated for Windows. Many Thanks.

**Comment by Ayuto** [comment]
Signatures have been updated 4 days ago. So, if the auto update is enabled, it should work already. This morning I also started a new build that also includes the updated signature. Please try again and let us know if it's working for you.

**Comment by LsLoki** [comment]
> Signatures have been updated 4 days ago. So, if the auto update is enabled, it should work already. This morning I also started a new build that also includes the updated signature. Please try again and let us know if it's working for you.

Version 724 works a treat on Windows. Will test with Linux later. Thank you very much!

**Comment by Lunacy1984** [comment]
I saw a loaded successfully, but I did have a crash before I could get in. Making sure that there is not a conflict issue with Source-metamod, sourcemod, and Hurricane bots.

**Comment by Lunacy1984** [comment]
Still a crash on joining.  The server will sit running until I try to join.

No other plugins running on a Source Dedicated server at my home on Windows 11. 
Most recent release of your download.  Console log with Sourcemod calls removed since that plugin is disabled.

[Source.Python] Loading...
[Source.Python] 
[SP] Encountered a Warning:
  File '..\addons\source-python\packages\site-packages\mutagen\id3\_specs.py', line 666: DeprecationWarning
    invalid escape sequence \s

[Source.Python] Loaded successfully.
maxplayers set to 16
maxplayers set to 16
Network: IP 192.168.1.104, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
CMaterialSystem::ReloadMaterials bDeviceReady false
Using map cycle file 'mapcycle.txt'.  ('cfg\mapcycle.txt' was not found.)
Error loading cfg/vscript_convar_allowlist.txt
VSCRIPT: Started VScript virtual machine using script language 'Squirrel'
Script not found (scripts/vscripts/mapspawn.nut) 
Precache of sprites/redglow1 ambigious (no extension specified)
Precache of sprites/redglow1 ambigious (no extension specified)
Precache of sprites/redglow1 ambigious (no extension specified)
Precache of sprites/redglow1 ambigious (no extension specified)
Set motd from file 'motd.txt'.  ('cfg/motd.txt' was not found.)
Set motd_text from file 'cfg/motd_text_default.txt'.  ('cfg/motd_text.txt' was not found.)
SV_ActivateServer: setting tickrate to 33.0
Writing cfg/banned_user.cfg.
Writing cfg/banned_ip.cfg.

--------------------------------------------------------
sv_pure value unchanged (current value is 0).
--------------------------------------------------------

Server is hibernating
Client "[PCP] Lunacy [1979] ☠" connected (192.168.1.7:27005).
Server waking up from hibernation

**Comment by LsLoki** [comment]
> > Signatures have been updated 4 days ago. So, if the auto update is enabled, it should work already. This morning I also started a new build that also includes the updated signature. Please try again and let us know if it's working for you.
> 
> Version 724 works a treat on Windows. Will test with Linux later. Thank you very much!

Yes same here, seems I spoke too soon. Version 724 loads fine and appears stable, loads the es emulator. But players are unable to join, the server does not crash it just hangs. Eliminated any conflict with SM or MM, tried with es emulator off, and any other SP plugins disabled. Only error in the log, 

Error loading cfg/vscript_convar_allowlist.txt
VSCRIPT: Started VScript virtual machine using script language 'Squirrel'
Script not found (scripts/vscripts/mapspawn.nut)

Problem resolved for players joining the server, by disabling Source Python.

**Comment by Lunacy1984** [comment]
Also of note from recording a video of only the base source-python and nothing else running.
This crash is not written in the log

Unable to find return address. You are going to crash now.
src\tier0\threadtools\.cpp (3465) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'
src\tier0\threadtools\.cpp (3465) : Assertion Failed: Illegal termination of worker thread 'CFileWriterThread'

**Comment by CookStar** [comment]
Since vtable has changed, that doesn't surprise me.

**Comment by CookStar** [comment]
This should solve the problem with SP data. #502

**Comment by LsLoki** [comment]
> This should solve the problem with SP data. #502

Indeed that allowed me to join the server again with SP v724 running. Thank you very much for detailing those revised offsets. I will do more testing.

**Comment by Lunacy1984** [comment]
Damn. I tried with this latest update and I was unable to join a fresh server with only the base source.python installed. Don't know what is left to eliminate.

[Source.Python] Loading...
[Source.Python] Loaded successfully.
maxplayers set to 16
maxplayers set to 16
Unknown command "autoupdate"
Unknown command "port"
Network: IP 192.168.1.104, mode MP, dedicated Yes, ports 27017 SV / 27005 CL
CMaterialSystem::ReloadMaterials bDeviceReady false
Using map cycle file 'cfg/mapcycle_default.txt'.  ('cfg\mapcycle.txt' was not found.)
Error loading cfg/vscript_convar_allowlist.txt
VSCRIPT: Started VScript virtual machine using script language 'Squirrel'
Script not found (scripts/vscripts/mapspawn.nut) 
Precache of sprites/redglow1 ambigious (no extension specified)
Precache of sprites/redglow1 ambigious (no extension specified)
Set motd from file 'cfg/motd_default.txt'.  ('cfg/motd.txt' was not found.)
Set motd_text from file 'cfg/motd_text_default.txt'.  ('cfg/motd_text.txt' was not found.)
SV_ActivateServer: setting tickrate to 33.0
'server.cfg' not present; not executing.
Server is hibernating
Client "[PCP] Lunacy [1979] ☠" connected (192.168.1.7:27005).
Server waking up from hibernation

**Comment by CookStar** [comment]
> Damn. I tried with this latest update and I was unable to join a fresh server with only the base source.python installed. Don't know what is left to eliminate.

Have you tried #502?

**Comment by Lunacy1984** [comment]
Thought I downloaded the one on the main page that was stated as updated. I will try it again when I am able.

**Comment by Lunacy1984** [comment]
I got in for a second before it crashed. I will reload it again when I get home.

**Comment by Lunacy1984** [comment]
Might be onto something now
Source-python has loaded along with metamod source, sourcemod, and I also have it working with bots. Now I just have to figure out the ES emulator

**Comment by CookStar** [comment]
You will have to download it from here as it is not yet merged.
https://github.com/CookStar/Source.Python/tree/hl2mp_v

Overwrite what is in the folder here.
https://github.com/CookStar/Source.Python/tree/hl2mp_v/addons/source-python/data/source-python/entities/orangebox/hl2mp

**Comment by Lunacy1984** [comment]
Dumb question, could someone point me to where I can add more plugins. I found tutorials and forums, but I can't find where I got the ES Emulator from.

**Comment by CookStar** [comment]
> Dumb question, could someone point me to where I can add more plugins. I found tutorials and forums, but I can't find where I got the ES Emulator from.

https://github.com/Ayuto/EventScripts-Emulator

**Comment by Lunacy1984** [comment]
I have that page, but I thought I found other source-python plugins. That is what I am looking for.

**Comment by CookStar** [comment]
I don't know which source-python plugins you are talking about.

**Comment by Lunacy1984** [comment]
ES_emulater is only one of the plugins that you can add to source-python. I know I saw more

**Comment by CookStar** [comment]
You mean you don't know how to install the plugin for Source.Python? I am not sure what you are asking.

**Comment by Lunacy1984** [comment]
1 Source-python is installed and running
2 ES emulator is installed and working
3 LOOKING FOR MORE PLUGINS that are for source-python like you would add to sourcemod for example

**Comment by CookStar** [comment]
I've never installed someone else's plugin, so I don't know, but you might want to check the [forums](https://forums.sourcepython.com/viewforum.php?f=7) or [ask on the forum](https://forums.sourcepython.com/viewforum.php?f=37).

**Comment by Ayuto** [comment]
Beside the links @CookStar provided you can also look for repositories tagged with source-python here on GitHub.

**Comment by LsLoki** [comment]
> I never really published the ES emulator officially. I just created the repository as a fun project. But the interest was bigger than expected.

Interest in your ES emulator (and Source Python that matter) is likely to gain a lot of momentum now that Mattie Eventscripts is officially dead. Earlier interest was likely from people preparing for this day. I run both Windows and Rental Linux servers, installation of of Source Python is straight forward on Windows but problematic on Linux, this given the dependencies on libz.so.1 and libffi6, [https://github.com/Source-Python-Dev-Team/Source.Python/issues/495](url) My server hosts have been sitting on a request to install libffi6 for over 8 days - likely thinking I'm crazy to be even asking? Either way I expect SP to be the big issue in the months ahead.

**Comment by CookStar** [comment]
Hey @Ayuto, this is not the right place to say this, but could you please take a look at the pull requests that have not received any replies at all? (#496,  #499, #501)

**Comment by Ayuto** [comment]
Yeah, I'm sorry... I haven't really had time to have a proper look at the issues you fixed with the PRs. Hopefully, that will change in mid of January.

**Comment by Lunacy1984** [comment]
Latest update Feb 18 has broken source-python for HL2DM again.

[Source.Python] Loading...
[Source.Python] Failed to load the main module due to following exception:
Traceback (most recent call last):

  File "c:\server\hl2dm_wcc\hl2mp\addons\source-python\packages\source-python\__init__.py", line 88, in load
    setup_global_pointers()

  File "c:\server\hl2dm_wcc\hl2mp\addons\source-python\packages\source-python\__init__.py", line 312, in setup_global_pointers
    server.server = server.engine_server.server

RuntimeError: Access violation - no RTTI data!
[Source.Python] Could not initialize python.
Failed to load plugin "addons/source-python"
[Source.Python] Unloading...
[Source.Python] Unloaded successfully.

**Comment by LsLoki** [comment]
Servers updated to version v9540945 ... SP 725 is working okay for me on Linux. On Windows it is not loading. Offsets checked for Linux, look unchanged. I have not checked for Windows yet.

**Comment by Ayuto** [comment]
Somehow Valve manages it to publish a new update everytime I'm not at home for a week... I will return on Sunday. So please don't expect a fix before Monday/Tuesday.

**Comment by LsLoki** [comment]
> Somehow Valve manages it to publish a new update everytime I'm not at home for a week... I will return on Sunday. So please don't expect a fix before Monday/Tuesday.

@Ayuto I have several plugins currently not working waiting for a new update of Source Python.  Are you making any progress?

**Comment by Ayuto** [comment]
I'm sorry for not replying earlier. This will be a bigger change as I need to upgrade to a newer C++ version. By doing that I also need to recompile all dependencies like Boost, Python, DynamicHooks, etc. Since I need to recompile I also decided to upgrade to the latest Python version. So, with the next update Source.Python will run with Python 3.13.

**Comment by CookStar** [comment]
I'm happy to hear that. Is Visual Studio 2022 the migration destination? Please let me know if there is anything I can do to help.

**Comment by Ayuto** [comment]
Yes, we will be using Visual Studio 2022. We should have done that much earlier, but well...

After the upgrade we also need to make some code changes to be able to successfully compile against the latest SDK. After that we will need to check/update the signatures and offsets. Any help regarding that is very much appreciated.

**Comment by verstatx** [comment]
I hacked together a build against the new TF2 SDK (builds and runs), but ran into binary compatibility issues due to my build environment. I know this isn't very helpful and probably late, but here's the starting point I got to with the new sdk: [verstatx/Source.Python/tree/tf2buildfix](https://github.com/verstatx/Source.Python/tree/tf2buildfix).

**Comment by LsLoki** [comment]
On my HL2M Linux servers Source Python appears to be conflicting with Metamod/Sourcemod. If I remove both SM/MM - Source Python loads. If I try to load all 3 I get a segmentation error and the server fails to load. If I disable SP SM/MM load. I need to run SM/MM, so currently this has killed SP on my Linux servers. (My windows servers await the new version of SP). 
I read #101 similar things were causing problems on CSGO - has a similar problem resurfaced?

**Comment by Ayuto** [comment]
Sorry, I still had no time to really work on this.

**Comment by LsLoki** [comment]
Anyone else on the Dev team able to help? Source Python has been broken just over one month now.

**Comment by wr6ngway** [comment]
any updates on the project?

**Comment by LsLoki** [comment]
> any updates on the project?

https://github.com/Ayuto/DynamicHooks

**Comment by Ayuto** [comment]
Closing this issue in favor of #505.
